// Commons 精選圖池：風景 + 建築（由 Commons API 蒐集、逐張人審標註；src 為 API 給的 960px 縮圖，勿手改寬度）
import type { CommonsImage } from '../types'

export const landscapeArchitecturePool: CommonsImage[] = [
  {
    // File:Frosty Raftsundet landscape with Trolltindan in morning, 2012 October.JPG
    id: "img-landscape-001",
    category: "landscape",
    title: "羅弗敦 Raftsundet 峽灣結霜清晨",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Frosty_Raftsundet_landscape_with_Trolltindan_in_morning%2C_2012_October.JPG/960px-Frosty_Raftsundet_landscape_with_Trolltindan_in_morning%2C_2012_October.JPG",
    width: 3246,
    height: 2151,
    author: "Ximonic (Simo Räsänen)",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Frosty_Raftsundet_landscape_with_Trolltindan_in_morning,_2012_October.JPG",
    tags: ["landscape", "horizon"],
    whyGood: "前景結霜的岩石與草地、中景鏡面般的海灣、遠景被晨光染金的山峰，三層前中後景把空間感撐開；水平線保持水平，山影完整倒映在靜水裡，冷色調的霜與暖色山頭形成對比。",
    principles: ["depth-layers", "horizon-level", "golden-hour"],
  },
  {
    // File:Blue Mountains National Park (AU), Three Sisters -- 2019 -- 1987-9.jpg
    id: "img-landscape-002",
    category: "landscape",
    title: "藍山國家公園三姊妹岩",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Blue_Mountains_National_Park_%28AU%29%2C_Three_Sisters_--_2019_--_1987-9.jpg/960px-Blue_Mountains_National_Park_%28AU%29%2C_Three_Sisters_--_2019_--_1987-9.jpg",
    width: 5973,
    height: 6191,
    author: "Dietmar Rabich",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Blue_Mountains_National_Park_(AU),_Three_Sisters_--_2019_--_1987-9.jpg",
    tags: ["landscape", "horizon"],
    whyGood: "左側桉樹當前景框邊，把視線推向被側光照亮的三姊妹岩；岩柱放在偏左三分線，右側留出層層遠山直到地平線，深綠森林襯托金黃砂岩，色彩對比乾淨。",
    principles: ["depth-layers", "rule-of-thirds", "light-direction"],
  },
  {
    // File:Seascape after sunset denoised.jpg
    id: "img-landscape-003",
    category: "landscape",
    title: "日落後的藍調海岸",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Seascape_after_sunset_denoised.jpg/960px-Seascape_after_sunset_denoised.jpg",
    width: 2640,
    height: 1760,
    author: "Rnbc (talk) at en.wikipedia",
    license: "CC BY-SA 3.0",
    licenseUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Seascape_after_sunset_denoised.jpg",
    tags: ["landscape", "horizon", "night", "minimal"],
    whyGood: "長時間曝光把海浪抹成霧狀，前景黑色礁石只留輪廓，兩座海蝕柱一左一右分置，中間大片漸層天空留白；海平線筆直，藍調時刻的冷色與地平線一抹粉橘形成安靜的對比。",
    principles: ["negative-space", "golden-hour", "shutter-motion"],
  },
  {
    // File:Sossusvlei Dune Namib Desert Namibia Luca Galuzzi 2004.JPG
    id: "img-landscape-004",
    category: "landscape",
    title: "Sossusvlei 沙丘的 S 形稜線",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Sossusvlei_Dune_Namib_Desert_Namibia_Luca_Galuzzi_2004.JPG/960px-Sossusvlei_Dune_Namib_Desert_Namibia_Luca_Galuzzi_2004.JPG",
    width: 2000,
    height: 1333,
    author: "Luca Galuzzi (Lucag)",
    license: "CC BY-SA 2.5",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.5",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sossusvlei_Dune_Namib_Desert_Namibia_Luca_Galuzzi_2004.JPG",
    tags: ["landscape", "minimal"],
    whyGood: "一條 S 形沙脊把畫面切成亮橘與深棕兩塊，稜線本身就是引導線；只有沙、影子與純藍天三種顏色，左上一個極小的人影點出沙丘的尺度，減法做到極致。",
    principles: ["leading-lines", "simplify", "color-harmony"],
  },
  {
    // File:Dead Vlei Tree central.jpg
    id: "img-landscape-005",
    category: "landscape",
    title: "Dead Vlei 枯樹與紅沙丘",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Dead_Vlei_Tree_central.jpg/960px-Dead_Vlei_Tree_central.jpg",
    width: 4600,
    height: 2759,
    author: "Daniel Kraft",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Dead_Vlei_Tree_central.jpg",
    tags: ["landscape", "horizon", "centered"],
    whyGood: "白色鹽地、橘紅沙丘、藍天三條色帶橫向分層，枯樹放在畫面中央偏右，樹影延伸到前景增加立體感；遠處第二棵枯樹作為呼應，避免主體孤立。",
    principles: ["color-harmony", "subject-placement", "depth-layers"],
  },
  {
    // File:Puente colgante sobre el cañón Lynn, Vancouver, Canadá, 2017-08-14, DD 10.jpg
    id: "img-landscape-006",
    category: "landscape",
    title: "Lynn Canyon 森林吊橋",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Puente_colgante_sobre_el_ca%C3%B1%C3%B3n_Lynn%2C_Vancouver%2C_Canad%C3%A1%2C_2017-08-14%2C_DD_10.jpg/960px-Puente_colgante_sobre_el_ca%C3%B1%C3%B3n_Lynn%2C_Vancouver%2C_Canad%C3%A1%2C_2017-08-14%2C_DD_10.jpg",
    width: 5726,
    height: 8589,
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Puente_colgante_sobre_el_ca%C3%B1%C3%B3n_Lynn,_Vancouver,_Canad%C3%A1,_2017-08-14,_DD_10.jpg",
    tags: ["landscape", "symmetric"],
    whyGood: "站在橋頭正中央拍攝，橋面木板與兩側鐵網收斂到遠端消失點，形成強烈的一點透視引導線；左右完全對稱，深綠森林把橋包成一個天然的框。",
    principles: ["leading-lines", "symmetry", "framing"],
  },
  {
    // File:Fanal (Madeira, Portugal), Lorbeerwald -- 2025 -- 1532.jpg
    id: "img-landscape-007",
    category: "landscape",
    title: "Madeira Fanal 霧中月桂樹",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Fanal_%28Madeira%2C_Portugal%29%2C_Lorbeerwald_--_2025_--_1532.jpg/960px-Fanal_%28Madeira%2C_Portugal%29%2C_Lorbeerwald_--_2025_--_1532.jpg",
    width: 6610,
    height: 4407,
    author: "Dietmar Rabich",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fanal_(Madeira,_Portugal),_Lorbeerwald_--_2025_--_1532.jpg",
    tags: ["landscape", "minimal", "highkey", "horizon"],
    whyGood: "白霧當作天然的乾淨背景，三棵扭曲的月桂樹剪影被清楚分離出來，互不重疊；綠色草坡占下方三分之一，其餘大面積留白，高調畫面安靜卻有張力。",
    principles: ["negative-space", "simplify", "rule-of-thirds"],
  },
  {
    // File:Mount Hood reflected in Mirror Lake, Oregon.jpg
    id: "img-landscape-008",
    category: "landscape",
    title: "Mirror Lake 倒映胡德山",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Mount_Hood_reflected_in_Mirror_Lake%2C_Oregon.jpg/960px-Mount_Hood_reflected_in_Mirror_Lake%2C_Oregon.jpg",
    width: 2048,
    height: 1626,
    author: "Oregon's Mt. Hood Territory.",
    license: "Public domain",
    licenseUrl: "https://commons.wikimedia.org/wiki/Commons:Licensing",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mount_Hood_reflected_in_Mirror_Lake,_Oregon.jpg",
    tags: ["landscape", "symmetric", "horizon"],
    whyGood: "湖面平靜如鏡，雪山、森林與天空被完整上下鏡射，中線就是岸邊，構成近乎完美的對稱；雪山放在中央偏上、兩側杉樹當框，深藍天讓白雪更突出。",
    principles: ["symmetry", "framing", "exposure"],
  },
  {
    // File:Jokulsarlon lake, Iceland.jpg
    id: "img-landscape-009",
    category: "landscape",
    title: "冰島 Jökulsárlón 冰河湖日落",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Jokulsarlon_lake%2C_Iceland.jpg/960px-Jokulsarlon_lake%2C_Iceland.jpg",
    width: 2921,
    height: 1931,
    author: "Kenny Muir",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Jokulsarlon_lake,_Iceland.jpg",
    tags: ["landscape", "horizon"],
    whyGood: "橘粉色的雲映在平靜的冰湖上，浮冰從前景散落到中景引導視線，山脈切在畫面中間偏上；前景右下的碎石灘提供立足點，讓畫面有深度而不是一片平面。",
    principles: ["golden-hour", "depth-layers", "horizon-level"],
  },
  {
    // File:Bontecou Lake Milky Way panorama.jpg
    id: "img-landscape-010",
    category: "landscape",
    title: "Bontecou 湖銀河拱橋",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Bontecou_Lake_Milky_Way_panorama.jpg/960px-Bontecou_Lake_Milky_Way_panorama.jpg",
    width: 9640,
    height: 3949,
    author: "Juliancolton",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bontecou_Lake_Milky_Way_panorama.jpg",
    tags: ["landscape", "night", "horizon"],
    whyGood: "銀河的弧線橫跨整個天空，兩端落在畫面左右邊緣，地平線與樹線保持水平；湖面倒映微弱星光，遠處城鎮光害被留在地平線上當作暖色點綴而非干擾。",
    principles: ["noise", "horizon-level", "shutter-motion"],
  },
  {
    // File:Glencoe Lochan reflections 3 20211022.jpg
    id: "img-landscape-011",
    category: "landscape",
    title: "Glencoe Lochan 秋色倒影",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Glencoe_Lochan_reflections_3_20211022.jpg/960px-Glencoe_Lochan_reflections_3_20211022.jpg",
    width: 9456,
    height: 3817,
    author: "Daniel Kraft",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Glencoe_Lochan_reflections_3_20211022.jpg",
    tags: ["landscape", "symmetric", "horizon"],
    whyGood: "無風的湖面把山丘、秋葉與雲層完整倒映，上下對稱得幾乎分不出哪邊是真的；一棵金黃色的樺樹放在畫面中央偏左當視覺焦點，柔和的陰天光讓色彩飽和但不刺眼。",
    principles: ["symmetry", "color-harmony", "golden-hour"],
  },
  {
    // File:Juan Griego Sunset.jpg
    id: "img-landscape-012",
    category: "landscape",
    title: "Juan Griego 漁港日落",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Juan_Griego_Sunset.jpg/960px-Juan_Griego_Sunset.jpg",
    width: 4288,
    height: 2443,
    author: "Wilfredor",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Juan_Griego_Sunset.jpg",
    tags: ["landscape", "horizon"],
    whyGood: "太陽落在上三分線附近，海平線保持水平，漁船左右錯落分佈而不擠在一起；整張只有橘色到米色的單一色系，前景沙灘與浪線帶出距離感，簡單卻完整。",
    principles: ["rule-of-thirds", "color-harmony", "horizon-level"],
  },
  {
    // File:Ramsau bei Berchtesgaden (DE), Milchstraße über Hochkalter & Hintersee -- 2024 -- 1018-50.jpg
    id: "img-landscape-013",
    category: "landscape",
    title: "Hintersee 銀河與山影倒映",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Ramsau_bei_Berchtesgaden_%28DE%29%2C_Milchstra%C3%9Fe_%C3%BCber_Hochkalter_%26_Hintersee_--_2024_--_1018-50.jpg/960px-Ramsau_bei_Berchtesgaden_%28DE%29%2C_Milchstra%C3%9Fe_%C3%BCber_Hochkalter_%26_Hintersee_--_2024_--_1018-50.jpg",
    width: 4000,
    height: 6000,
    author: "Anil Öztas",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ramsau_bei_Berchtesgaden_(DE),_Milchstra%C3%9Fe_%C3%BCber_Hochkalter_%26_Hintersee_--_2024_--_1018-50.jpg",
    tags: ["landscape", "night", "symmetric", "minimal"],
    whyGood: "直幅讓銀河從天頂垂直流向山峰，山與倒影在底部形成上下對稱的黑色剪影；天空占據八成畫面的大量留白反而突顯銀河，長曝光把星點記錄得乾淨清晰。",
    principles: ["negative-space", "symmetry", "noise"],
  },
  {
    // File:Blassenstein Kreuz mit Nebel 01.JPG
    id: "img-landscape-014",
    category: "landscape",
    title: "Blassenstein 山頂十字與雲海",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Blassenstein_Kreuz_mit_Nebel_01.JPG/960px-Blassenstein_Kreuz_mit_Nebel_01.JPG",
    width: 4000,
    height: 6000,
    author: "Uoaei1",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Blassenstein_Kreuz_mit_Nebel_01.JPG",
    tags: ["landscape", "centered", "horizon"],
    whyGood: "鐵製十字架刻意放在正中央，背後是平鋪的雲海與遠山，地平線保持水平；直幅把天空、雲海、岩石分成上中下三段，十字的鏤空紋樣在雲海白色背景上格外清楚。",
    principles: ["subject-placement", "depth-layers", "dynamic-range"],
  },
  {
    // File:Taiwan 2009 HuaLien City CiSingTan Bay First Light FRD 8235.jpg
    id: "img-landscape-015",
    category: "landscape",
    title: "花蓮七星潭清晨浪花",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Taiwan_2009_HuaLien_City_CiSingTan_Bay_First_Light_FRD_8235.jpg/960px-Taiwan_2009_HuaLien_City_CiSingTan_Bay_First_Light_FRD_8235.jpg",
    width: 4146,
    height: 2735,
    author: "Fred Hsu (Wikipedia:User:Fred Hsu on en.wikipedia)",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Taiwan_2009_HuaLien_City_CiSingTan_Bay_First_Light_FRD_8235.jpg",
    tags: ["landscape", "horizon"],
    whyGood: "蹲低讓破碎的白色浪沫佈滿下半部當前景，遠景是雲霧纏繞的海岸山脈；快門凝結飛濺的水珠，冷藍綠的色調統一整張畫面，海平線放在上三分線。",
    principles: ["perspective", "shutter-motion", "depth-layers"],
  },
  {
    // File:Dawu Mt+Hunag Chung Yu黃中佑+17755.jpg
    id: "img-landscape-016",
    category: "landscape",
    title: "大武山雲海",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Dawu_Mt%2BHunag_Chung_Yu%E9%BB%83%E4%B8%AD%E4%BD%91%2B17755.jpg/960px-Dawu_Mt%2BHunag_Chung_Yu%E9%BB%83%E4%B8%AD%E4%BD%91%2B17755.jpg",
    width: 7674,
    height: 3869,
    author: "Huang Chung Yu",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Dawu_Mt%2BHunag_Chung_Yu%E9%BB%83%E4%B8%AD%E4%BD%91%2B17755.jpg",
    tags: ["landscape"],
    whyGood: "左側綠色灌叢當前景框住畫面一角，稜線從左上斜向帶到中央山峰，右下方大片雲海留白讓畫面有呼吸空間；藍天、綠山、白雲三色乾淨，層次分明。",
    principles: ["depth-layers", "leading-lines", "negative-space"],
  },
  {
    // File:Дивовижне каміння Південного Бугу.jpg
    id: "img-landscape-017",
    category: "landscape",
    title: "南布格河岸的岩石水窪",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/%D0%94%D0%B8%D0%B2%D0%BE%D0%B2%D0%B8%D0%B6%D0%BD%D0%B5_%D0%BA%D0%B0%D0%BC%D1%96%D0%BD%D0%BD%D1%8F_%D0%9F%D1%96%D0%B2%D0%B4%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE_%D0%91%D1%83%D0%B3%D1%83.jpg/960px-%D0%94%D0%B8%D0%B2%D0%BE%D0%B2%D0%B8%D0%B6%D0%BD%D0%B5_%D0%BA%D0%B0%D0%BC%D1%96%D0%BD%D0%BD%D1%8F_%D0%9F%D1%96%D0%B2%D0%B4%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE_%D0%91%D1%83%D0%B3%D1%83.jpg",
    width: 2654,
    height: 4000,
    author: "Vian",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%D0%94%D0%B8%D0%B2%D0%BE%D0%B2%D0%B8%D0%B6%D0%BD%D0%B5_%D0%BA%D0%B0%D0%BC%D1%96%D0%BD%D0%BD%D1%8F_%D0%9F%D1%96%D0%B2%D0%B4%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE_%D0%91%D1%83%D0%B3%D1%83.jpg",
    tags: ["landscape"],
    whyGood: "前景兩塊巨石之間的水窪填滿綠色浮萍，形成一個天然的圓形框，往上帶到湍流與遠處逆光的日落；直幅把前中後景垂直堆疊，暖色的天空與冷色的水面形成對比。",
    principles: ["depth-layers", "framing", "golden-hour"],
  },
  {
    // File:Mealt Waterfall with Kilt Rock, Isle of Skye.jpg
    id: "img-landscape-018",
    category: "landscape",
    title: "斯凱島 Kilt Rock 瀑布",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Mealt_Waterfall_with_Kilt_Rock%2C_Isle_of_Skye.jpg/960px-Mealt_Waterfall_with_Kilt_Rock%2C_Isle_of_Skye.jpg",
    width: 6000,
    height: 9000,
    author: "Colin",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mealt_Waterfall_with_Kilt_Rock,_Isle_of_Skye.jpg",
    tags: ["landscape", "horizon"],
    whyGood: "瀑布沿著左側懸崖垂直落下，形成一條強烈的縱向線，右側大片海面留白平衡畫面；遠處海平線保持水平，崖底散落的石塊提供前景細節，高視角俯拍帶出高度感。",
    principles: ["leading-lines", "negative-space", "perspective"],
  },
  {
    // File:Rubjerg Knude Fyr, Hjørring, Denmark, 1807072231, ako.jpg
    id: "img-landscape-019",
    category: "landscape",
    title: "Rubjerg Knude 燈塔與沙丘",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Rubjerg_Knude_Fyr%2C_Hj%C3%B8rring%2C_Denmark%2C_1807072231%2C_ako.jpg/960px-Rubjerg_Knude_Fyr%2C_Hj%C3%B8rring%2C_Denmark%2C_1807072231%2C_ako.jpg",
    width: 6720,
    height: 4480,
    author: "Ansgar Koreng",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Rubjerg_Knude_Fyr,_Hj%C3%B8rring,_Denmark,_1807072231,_ako.jpg",
    tags: ["landscape", "minimal", "horizon"],
    whyGood: "粉紫漸層的日落天空占上半部，燈塔放在右側三分線上，海平線筆直橫過畫面中央；前景沙丘的波紋提供質感，沒有任何多餘元素，是減法構圖的示範。",
    principles: ["rule-of-thirds", "simplify", "golden-hour"],
  },
  {
    // File:Smoke from the 2020 California wildfires tinting the sunset red on the Swedish west coast 3.jpg
    id: "img-landscape-020",
    category: "landscape",
    title: "野火煙霧下的瑞典西岸日落",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Smoke_from_the_2020_California_wildfires_tinting_the_sunset_red_on_the_Swedish_west_coast_3.jpg/960px-Smoke_from_the_2020_California_wildfires_tinting_the_sunset_red_on_the_Swedish_west_coast_3.jpg",
    width: 5472,
    height: 3263,
    author: "W.carter",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Smoke_from_the_2020_California_wildfires_tinting_the_sunset_red_on_the_Swedish_west_coast_3.jpg",
    tags: ["landscape", "minimal", "horizon", "lowkey"],
    whyGood: "整張只有橘色漸層與黑色剪影兩種元素，島嶼與小燈塔橫排在下方，海平線筆直；曝光刻意保留天空色彩讓地面全黑，低調畫面把重點交給顏色與線條。",
    principles: ["exposure", "color-harmony", "horizon-level"],
  },
  {
    // File:Dülmen, Leuste, Bäume im Nebel -- 2020 -- 5042 (bw).jpg
    id: "img-landscape-021",
    category: "landscape",
    title: "Dülmen 霧中田間路",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/D%C3%BClmen%2C_Leuste%2C_B%C3%A4ume_im_Nebel_--_2020_--_5042_%28bw%29.jpg/960px-D%C3%BClmen%2C_Leuste%2C_B%C3%A4ume_im_Nebel_--_2020_--_5042_%28bw%29.jpg",
    width: 6447,
    height: 4298,
    author: "Dietmar Rabich",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:D%C3%BClmen,_Leuste,_B%C3%A4ume_im_Nebel_--_2020_--_5042_(bw).jpg",
    tags: ["landscape", "bw", "minimal", "horizon"],
    whyGood: "黑白讓枝椏的線條成為主角，右側大樹佔畫面一半、左側大片白霧留白形成不對稱的平衡；田間路從底部直直收斂到消失點，霧氣把遠處的樹一層層淡出，空間感很強。",
    principles: ["negative-space", "leading-lines", "simplify"],
  },
  {
    // File:Dülmen, Merfeld, Feldweg am Mühlenbach -- 2021 -- 4278-80.jpg
    id: "img-landscape-022",
    category: "landscape",
    title: "Mühlenbach 田間路日出",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/D%C3%BClmen%2C_Merfeld%2C_Feldweg_am_M%C3%BChlenbach_--_2021_--_4278-80.jpg/960px-D%C3%BClmen%2C_Merfeld%2C_Feldweg_am_M%C3%BChlenbach_--_2021_--_4278-80.jpg",
    width: 6703,
    height: 4469,
    author: "Dietmar Rabich",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:D%C3%BClmen,_Merfeld,_Feldweg_am_M%C3%BChlenbach_--_2021_--_4278-80.jpg",
    tags: ["landscape", "horizon"],
    whyGood: "柏油路從左下角 S 形彎向遠處，一排樹沿路排列成第二條引導線，兩者都指向消失點；粉橘色的日出雲彩占上半部，地平線保持水平，冷暖色調平衡。",
    principles: ["leading-lines", "golden-hour", "horizon-level"],
  },
  {
    // File:Riga Cathedral Nave, Riga, Latvia - Diliff.jpg
    id: "img-architecture-001",
    category: "architecture",
    title: "里加主教座堂中殿",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Riga_Cathedral_Nave%2C_Riga%2C_Latvia_-_Diliff.jpg/960px-Riga_Cathedral_Nave%2C_Riga%2C_Latvia_-_Diliff.jpg",
    width: 6453,
    height: 6530,
    author: "Diliff",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Riga_Cathedral_Nave,_Riga,_Latvia_-_Diliff.jpg",
    tags: ["architecture", "symmetric", "centered"],
    whyGood: "站在中軸線正中央拍攝，紅地毯直通祭壇，兩側長椅、石柱與拱頂完全左右對稱；白牆襯出紅磚拱肋的線條，垂直線保持垂直，是建築對稱構圖最標準的示範。",
    principles: ["symmetry", "leading-lines", "horizon-level"],
  },
  {
    // File:Laon Cathedral Interior 04.JPG
    id: "img-architecture-002",
    category: "architecture",
    title: "拉昂主教座堂中殿俯視",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Laon_Cathedral_Interior_04.JPG/960px-Laon_Cathedral_Interior_04.JPG",
    width: 3078,
    height: 4616,
    author: "Uoaei1",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Laon_Cathedral_Interior_04.JPG",
    tags: ["architecture", "symmetric"],
    whyGood: "從高處樓座俯拍，尖拱層層疊向盡頭的玫瑰窗，所有線條都收斂到同一點；石柱垂直線筆直，直幅把挑高感拉到極限，柔和的自然光讓石材質感細膩不死白。",
    principles: ["leading-lines", "symmetry", "exposure"],
  },
  {
    // File:St Paul's Cathedral Interior Dome 3, London, UK - Diliff.jpg
    id: "img-architecture-003",
    category: "architecture",
    title: "聖保羅座堂穹頂正仰視",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/St_Paul%27s_Cathedral_Interior_Dome_3%2C_London%2C_UK_-_Diliff.jpg/960px-St_Paul%27s_Cathedral_Interior_Dome_3%2C_London%2C_UK_-_Diliff.jpg",
    width: 6000,
    height: 6009,
    author: "Diliff",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:St_Paul%27s_Cathedral_Interior_Dome_3,_London,_UK_-_Diliff.jpg",
    tags: ["architecture", "symmetric", "centered"],
    whyGood: "鏡頭垂直朝上，圓形穹頂放在正中央，四角金色拱頂呈輻射狀對稱，構成一個完美的圓與方；曝光顧到窗戶亮部與彩繪暗部，金色與藍色的配色統一整張畫面。",
    principles: ["symmetry", "subject-placement", "dynamic-range"],
  },
  {
    // File:Sydney Harbour Bridge night.jpg
    id: "img-architecture-004",
    category: "architecture",
    title: "雪梨港灣大橋夜景全景",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Sydney_Harbour_Bridge_night.jpg/960px-Sydney_Harbour_Bridge_night.jpg",
    width: 13742,
    height: 3431,
    author: "Diliff",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sydney_Harbour_Bridge_night.jpg",
    tags: ["architecture", "night", "horizon"],
    whyGood: "海平面保持水平貫穿整張全景，橋拱的燈光與城市天際線映在水面；歌劇院在左邊當配角，橋塔在右邊當主角，長曝光讓水面平滑、燈光清晰而不過曝。",
    principles: ["horizon-level", "shutter-motion", "exposure"],
  },
  {
    // File:Brooklyn Bridge - 03.jpg
    id: "img-architecture-005",
    category: "architecture",
    title: "布魯克林橋藍調時刻車軌",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Brooklyn_Bridge_-_03.jpg/960px-Brooklyn_Bridge_-_03.jpg",
    width: 2000,
    height: 3000,
    author: "Carlos Delgado",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Brooklyn_Bridge_-_03.jpg",
    tags: ["architecture", "night"],
    whyGood: "藍調時刻的天空與暖黃車燈拖影形成冷暖對比，鋼索與車道線條全部收斂到遠處橋塔；直幅把車軌拉長，長曝光把車流變成金色光帶，前景橫梁提供層次。",
    principles: ["shutter-motion", "leading-lines", "golden-hour"],
  },
  {
    // File:Tower Bridge Lights.jpg
    id: "img-architecture-006",
    category: "architecture",
    title: "倫敦塔橋夜拍車燈拖影",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Tower_Bridge_Lights.jpg/960px-Tower_Bridge_Lights.jpg",
    width: 2826,
    height: 4239,
    author: "Martin Falbisoner",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tower_Bridge_Lights.jpg",
    tags: ["architecture", "night", "lowkey"],
    whyGood: "主塔置中打光，左右藍色鋼架與欄杆從兩側引導視線到橋塔，右側紅色車燈拖出流動的線條；天空純黑讓建築燈光成為唯一主角，垂直線保持垂直。",
    principles: ["leading-lines", "shutter-motion", "exposure"],
  },
  {
    // File:Boat passing under Elgin Bridge during blue hour (2023)-L1003785.jpg
    id: "img-architecture-007",
    category: "architecture",
    title: "新加坡 Elgin Bridge 藍調時刻",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Boat_passing_under_Elgin_Bridge_during_blue_hour_%282023%29-L1003785.jpg/960px-Boat_passing_under_Elgin_Bridge_during_blue_hour_%282023%29-L1003785.jpg",
    width: 9332,
    height: 6198,
    author: "Frank Schulenburg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Boat_passing_under_Elgin_Bridge_during_blue_hour_(2023)-L1003785.jpg",
    tags: ["architecture", "night", "horizon"],
    whyGood: "白色拱橋配藍色燈帶，藍調時刻的天空與燈光同色系，水面倒影完整；長曝光讓經過的船隻拖出紅綠光軌增加動感，右側欄杆當前景引導視線進入畫面。",
    principles: ["golden-hour", "shutter-motion", "depth-layers"],
  },
  {
    // File:Kopenhagen (DK), Bahnhof -- 2017 -- 1672 (bw).jpg
    id: "img-architecture-008",
    category: "architecture",
    title: "哥本哈根車站樓梯黑白俯視",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Kopenhagen_%28DK%29%2C_Bahnhof_--_2017_--_1672_%28bw%29.jpg/960px-Kopenhagen_%28DK%29%2C_Bahnhof_--_2017_--_1672_%28bw%29.jpg",
    width: 5347,
    height: 3565,
    author: "Dietmar Rabich",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kopenhagen_(DK),_Bahnhof_--_2017_--_1672_(bw).jpg",
    tags: ["architecture", "bw", "symmetric"],
    whyGood: "從樓梯頂端俯拍，扶手與兩側鐵軌形成完美的左右對稱，所有線條收斂到月台中央的時鐘；黑白去掉顏色干擾，只剩幾何線條與明暗，重複的階梯紋理成為畫面節奏。",
    principles: ["symmetry", "leading-lines", "simplify"],
  },
  {
    // File:Hyogo Prefectural Museum of Art spiral staircase Kobe 2026 dllu.jpg
    id: "img-architecture-009",
    category: "architecture",
    title: "兵庫縣立美術館清水混凝土螺旋梯",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Hyogo_Prefectural_Museum_of_Art_spiral_staircase_Kobe_2026_dllu.jpg/960px-Hyogo_Prefectural_Museum_of_Art_spiral_staircase_Kobe_2026_dllu.jpg",
    width: 11447,
    height: 8464,
    author: "Daniel Lu (User:dllu)",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Hyogo_Prefectural_Museum_of_Art_spiral_staircase_Kobe_2026_dllu.jpg",
    tags: ["architecture", "minimal", "centered"],
    whyGood: "俯視角度把橢圓形螺旋梯放在正中央，整張只有灰色一種顏色，靠光影與雨漬紋理做出層次；曲線一圈圈往內收，觀者視線自然被帶到中心，減法構圖的代表。",
    principles: ["simplify", "leading-lines", "perspective"],
  },
  {
    // File:Bonn, Post-Tower -- 2017 -- 2128 (bw).jpg
    id: "img-architecture-010",
    category: "architecture",
    title: "波昂郵政大樓黑白仰拍",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Bonn%2C_Post-Tower_--_2017_--_2128_%28bw%29.jpg/960px-Bonn%2C_Post-Tower_--_2017_--_2128_%28bw%29.jpg",
    width: 5472,
    height: 3648,
    author: "Dietmar Rabich",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bonn,_Post-Tower_--_2017_--_2128_(bw).jpg",
    tags: ["architecture", "bw"],
    whyGood: "從地面仰拍，格狀雨棚斜切畫面右下，玻璃高塔的弧線從左下往右上延伸，兩者形成對角線的張力；黑白讓雲層紋理與建築的網格線條互相呼應，硬光把立體感拉出來。",
    principles: ["perspective", "leading-lines", "light-direction"],
  },
  {
    // File:Kaohsiung Taiwan Kaohsiung-Confucius-Temple-01.jpg
    id: "img-architecture-011",
    category: "architecture",
    title: "高雄孔廟大成殿",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Kaohsiung_Taiwan_Kaohsiung-Confucius-Temple-01.jpg/960px-Kaohsiung_Taiwan_Kaohsiung-Confucius-Temple-01.jpg",
    width: 5529,
    height: 3110,
    author: "CEphoto, Uwe Aranas",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kaohsiung_Taiwan_Kaohsiung-Confucius-Temple-01.jpg",
    tags: ["architecture", "symmetric", "centered", "horizon"],
    whyGood: "正面平視，屋頂、柱子、台階、欄杆左右完全對稱，地面與屋簷的水平線都保持水平；晴天順光讓橘黃屋瓦與藍天形成互補色，畫面乾淨沒有雜物。",
    principles: ["symmetry", "horizon-level", "color-harmony"],
  },
  {
    // File:淡水鄞山寺.jpg
    id: "img-architecture-012",
    category: "architecture",
    title: "淡水鄞山寺中庭",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/%E6%B7%A1%E6%B0%B4%E9%84%9E%E5%B1%B1%E5%AF%BA.jpg/960px-%E6%B7%A1%E6%B0%B4%E9%84%9E%E5%B1%B1%E5%AF%BA.jpg",
    width: 5472,
    height: 3648,
    author: "李秉樺",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%E6%B7%A1%E6%B0%B4%E9%84%9E%E5%B1%B1%E5%AF%BA.jpg",
    tags: ["architecture", "symmetric"],
    whyGood: "兩側廂房的屋簷從左右框住中央正殿，形成天然的框中框，燕尾脊左右對稱；香爐放在中軸線上當前景，藍天白雲補足上方空間，廣角帶出中庭的深度。",
    principles: ["framing", "symmetry", "depth-layers"],
  },
  {
    // File:Egeskov Slot spejling Edit 2.jpg
    id: "img-architecture-013",
    category: "architecture",
    title: "伊埃斯科城堡水面倒影",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Egeskov_Slot_spejling_Edit_2.jpg/960px-Egeskov_Slot_spejling_Edit_2.jpg",
    width: 1723,
    height: 1200,
    author: "Malene Thyssen",
    license: "CC BY-SA 3.0",
    licenseUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Egeskov_Slot_spejling_Edit_2.jpg",
    tags: ["architecture", "symmetric", "horizon"],
    whyGood: "護城河靜如鏡面，紅磚城堡與塔樓完整倒映，水岸線是畫面的水平軸；右上方的樹枝當前景框住一角，讓對稱畫面多了層次而不呆板，藍天襯托紅磚的暖色。",
    principles: ["symmetry", "framing", "depth-layers"],
  },
  {
    // File:Kiyomizu-dera, Kyoto, November 2016 -07.jpg
    id: "img-architecture-014",
    category: "architecture",
    title: "京都清水寺三重塔夜間點燈",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Kiyomizu-dera%2C_Kyoto%2C_November_2016_-07.jpg/960px-Kiyomizu-dera%2C_Kyoto%2C_November_2016_-07.jpg",
    width: 2942,
    height: 3922,
    author: "Martin Falbisoner",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kiyomizu-dera,_Kyoto,_November_2016_-07.jpg",
    tags: ["architecture", "night", "lowkey"],
    whyGood: "暖橘色的塔身在深藍夜空下格外突出，紅葉樹叢從下方包圍塔基形成前景；塔放在右側三分線，左上方大片黑暗留白，右上一束探照光斜切進來打破單調。",
    principles: ["rule-of-thirds", "exposure", "color-harmony"],
  },
  {
    // File:Long Room Interior, Trinity College Dublin, Ireland - Diliff.jpg
    id: "img-architecture-015",
    category: "architecture",
    title: "都柏林三一學院長廳",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Long_Room_Interior%2C_Trinity_College_Dublin%2C_Ireland_-_Diliff.jpg/960px-Long_Room_Interior%2C_Trinity_College_Dublin%2C_Ireland_-_Diliff.jpg",
    width: 9000,
    height: 6796,
    author: "Diliff",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Long_Room_Interior,_Trinity_College_Dublin,_Ireland_-_Diliff.jpg",
    tags: ["architecture", "symmetric"],
    whyGood: "站在長廳中軸線上，拱形木頂與兩排書櫃的線條收斂到盡頭，胸像沿中線排列成節奏；暖黃色地板反光讓畫面底部不會太暗，木頭與書的褐色統一整張色調。",
    principles: ["leading-lines", "symmetry", "color-harmony"],
  },
  {
    // File:Aks The Reflection Taj Mahal.jpg
    id: "img-architecture-016",
    category: "architecture",
    title: "泰姬瑪哈陵雨後倒影",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Aks_The_Reflection_Taj_Mahal.jpg/960px-Aks_The_Reflection_Taj_Mahal.jpg",
    width: 4928,
    height: 3264,
    author: "Antrix3",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Aks_The_Reflection_Taj_Mahal.jpg",
    tags: ["architecture", "symmetric", "horizon"],
    whyGood: "雨後的水面把陵墓與藍天白雲完整鏡射，形成上下對稱，水岸線放在中間偏下；主體置中而兩側的紅砂岩建築對稱陪襯，蹲低貼近水面才能讓倒影這麼完整。",
    principles: ["symmetry", "perspective", "horizon-level"],
  },
  {
    // File:Water reflection of canal houses at blue hour in Damrak Amsterdam the Netherlands.jpg
    id: "img-architecture-017",
    category: "architecture",
    title: "阿姆斯特丹運河屋藍調時刻",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Water_reflection_of_canal_houses_at_blue_hour_in_Damrak_Amsterdam_the_Netherlands.jpg/960px-Water_reflection_of_canal_houses_at_blue_hour_in_Damrak_Amsterdam_the_Netherlands.jpg",
    width: 5388,
    height: 4310,
    author: "Basile Morin",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Water_reflection_of_canal_houses_at_blue_hour_in_Damrak_Amsterdam_the_Netherlands.jpg",
    tags: ["architecture", "night", "horizon"],
    whyGood: "正面平視一排運河屋，每戶窗光顏色不同卻被藍調天空統一起來；建築的垂直線保持垂直，水面倒影拉出一條條光帶，長曝光讓運河平滑如鏡，顏色飽和而不刺眼。",
    principles: ["golden-hour", "horizon-level", "color-harmony"],
  },
  {
    // File:Water reflection of Hyangwonjeong Pavilion at Gyeongbokgung Palace in Seoul.jpg
    id: "img-architecture-018",
    category: "architecture",
    title: "景福宮香遠亭倒影",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Water_reflection_of_Hyangwonjeong_Pavilion_at_Gyeongbokgung_Palace_in_Seoul.jpg/960px-Water_reflection_of_Hyangwonjeong_Pavilion_at_Gyeongbokgung_Palace_in_Seoul.jpg",
    width: 3851,
    height: 5777,
    author: "Basile Morin",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Water_reflection_of_Hyangwonjeong_Pavilion_at_Gyeongbokgung_Palace_in_Seoul.jpg",
    tags: ["architecture", "symmetric", "centered", "horizon"],
    whyGood: "六角亭刻意放在正中央，池水把亭子、樹與遠山完整倒映，形成上下對稱；直幅讓天空、亭子、倒影各占一段，柔和的陰天光讓綠色與藍色都不過飽和。",
    principles: ["symmetry", "subject-placement", "saturation"],
  },
  {
    // File:Charlton House - tower detail - Jan 2026.jpg
    id: "img-architecture-019",
    category: "architecture",
    title: "Charlton House 塔樓細部",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Charlton_House_-_tower_detail_-_Jan_2026.jpg/960px-Charlton_House_-_tower_detail_-_Jan_2026.jpg",
    width: 4000,
    height: 6000,
    author: "Dominic Nelson",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Charlton_House_-_tower_detail_-_Jan_2026.jpg",
    tags: ["architecture", "minimal"],
    whyGood: "黃金時刻的低角度側光把紅磚的紋理打亮，塔樓置中，上方大面積的純藍天留白讓風向標成為視覺終點；長焦壓縮讓煙囪排成整齊的節奏，畫面沒有一絲雜物。",
    principles: ["golden-hour", "negative-space", "light-direction"],
  },
  {
    // File:Duisburg, Landschaftspark Duisburg-Nord, Hochofenstraße -- 2025 -- 7441.jpg
    id: "img-architecture-020",
    category: "architecture",
    title: "杜伊斯堡北部景觀公園夜間燈光",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Duisburg%2C_Landschaftspark_Duisburg-Nord%2C_Hochofenstra%C3%9Fe_--_2025_--_7441.jpg/960px-Duisburg%2C_Landschaftspark_Duisburg-Nord%2C_Hochofenstra%C3%9Fe_--_2025_--_7441.jpg",
    width: 3776,
    height: 4720,
    author: "Dietmar Rabich",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Duisburg,_Landschaftspark_Duisburg-Nord,_Hochofenstra%C3%9Fe_--_2025_--_7441.jpg",
    tags: ["architecture", "night", "lowkey"],
    whyGood: "廢棄鋼鐵廠被紫、藍、綠燈光染色，前景暖色地面與背景冷色鋼架形成對比；黑色的柱子和樓梯當作框，把視線引向中央被藍光照亮的階梯，低調曝光讓顏色更濃。",
    principles: ["framing", "color-harmony", "exposure"],
  },
  {
    // File:Toronto - ON - CN Tower bei Nacht2.jpg
    id: "img-architecture-021",
    category: "architecture",
    title: "多倫多 CN Tower 藍調時刻",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Toronto_-_ON_-_CN_Tower_bei_Nacht2.jpg/960px-Toronto_-_ON_-_CN_Tower_bei_Nacht2.jpg",
    width: 2848,
    height: 4288,
    author: "Wladyslaw, Correction of perspective distortion: Niabot",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Toronto_-_ON_-_CN_Tower_bei_Nacht2.jpg",
    tags: ["architecture", "night", "landscape", "horizon"],
    whyGood: "藍調時刻的天空還留有顏色，城市燈光剛亮起，兩者亮度平衡讓細節都保得住；塔身垂直筆直放在中央偏右，直幅強調高度，水面倒影與水平線在底部收尾。",
    principles: ["golden-hour", "exposure", "horizon-level"],
  },
  {
    // File:Lower Manhattan from Jersey City November 2014 panorama 3.jpg
    id: "img-architecture-022",
    category: "architecture",
    title: "曼哈頓下城藍調全景",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Lower_Manhattan_from_Jersey_City_November_2014_panorama_3.jpg/960px-Lower_Manhattan_from_Jersey_City_November_2014_panorama_3.jpg",
    width: 9250,
    height: 3700,
    author: "King of Hearts",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lower_Manhattan_from_Jersey_City_November_2014_panorama_3.jpg",
    tags: ["architecture", "landscape", "horizon", "night"],
    whyGood: "從對岸隔著河拍攝，水平線筆直貫穿全景，建築的垂直線也保持垂直沒有傾斜；藍調時刻讓天空、水面與玻璃大樓同屬冷色系，暖色窗光成為點綴，長曝光把水面抹平。",
    principles: ["horizon-level", "golden-hour", "shutter-motion"],
  },
]
