// Wikimedia Commons 精選圖池：people-animals（動物為主）+ still-life（食物/花卉/物件）。
// 由 Commons API 搜尋（Featured pictures / Quality images 為主），逐張人審標籤；
// src 為 API 回傳的 960px 縮圖（thumb 路徑原樣、僅換回 upload.wikimedia.org 主機並去除追蹤參數），
// 全部以 Range 請求驗證可用。授權僅收 CC0 / Public domain / CC BY / CC BY-SA。
import type { CommonsImage } from "../types"

export const peopleStillLifePool: CommonsImage[] = [
  {
    id: "img-people-animals-001",
    category: "people-animals",
    title: "枯枝上的翠鳥",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Common_Kingfisher_2025_09_28_03.jpg/960px-Common_Kingfisher_2025_09_28_03.jpg",
    width: 5993,
    height: 3995,
    author: "Alexis Lours",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Common_Kingfisher_2025_09_28_03.jpg",
    tags: ["portrait", "minimal"],
    whyGood:
      "翠鳥放在左側三分線上，枯枝從左下斜向右上把視線帶到鳥身；背景拉遠後虛化成一片乾淨的橄欖綠，橘藍羽色因此跳出來，眼睛銳利。",
    principles: ["rule-of-thirds", "leading-lines", "depth-of-field"],
  },
  {
    id: "img-people-animals-002",
    category: "people-animals",
    title: "單腳站立的穴鴞",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Athene_cunicularia_-near_Goiania%2C_Goias%2C_Brazil-8_edit.jpg/960px-Athene_cunicularia_-near_Goiania%2C_Goias%2C_Brazil-8_edit.jpg",
    width: 2160,
    height: 3060,
    author: "Wagner Machado Carlos Lemes from Goiânia, Brazil; derivative work by King of Hea",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Athene_cunicularia_-near_Goiania,_Goias,_Brazil-8_edit.jpg",
    tags: ["portrait", "centered", "minimal"],
    whyGood:
      "主體刻意置中、正面對視，柔焦的綠紅色塊當背景，讓黃眼睛成為唯一焦點；對焦精準落在眼睛，直幅把單腳站姿完整收進來，底部留出木樁。",
    principles: ["depth-of-field", "sharpness", "subject-placement"],
  },
  {
    id: "img-people-animals-003",
    category: "people-animals",
    title: "火山前的紅狐",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/%D0%9B%D0%B8%D1%81%D0%B0-%D0%BE%D0%B3%D0%BD%D0%B5%D0%B2%D0%BA%D0%B0_%D0%BD%D0%B0_%D1%84%D0%BE%D0%BD%D0%B5_%D0%92%D0%B8%D0%BB%D1%8E%D1%87%D0%B8%D0%BD%D1%81%D0%BA%D0%BE%D0%B3%D0%BE_%D0%B2%D1%83%D0%BB%D0%BA%D0%B0%D0%BD%D0%B0.jpg/960px-%D0%9B%D0%B8%D1%81%D0%B0-%D0%BE%D0%B3%D0%BD%D0%B5%D0%B2%D0%BA%D0%B0_%D0%BD%D0%B0_%D1%84%D0%BE%D0%BD%D0%B5_%D0%92%D0%B8%D0%BB%D1%8E%D1%87%D0%B8%D0%BD%D1%81%D0%BA%D0%BE%D0%B3%D0%BE_%D0%B2%D1%83%D0%BB%D0%BA%D0%B0%D0%BD%D0%B0.jpg",
    width: 5931,
    height: 4178,
    author: "NadezhdaKhaustova",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%D0%9B%D0%B8%D1%81%D0%B0-%D0%BE%D0%B3%D0%BD%D0%B5%D0%B2%D0%BA%D0%B0_%D0%BD%D0%B0_%D1%84%D0%BE%D0%BD%D0%B5_%D0%92%D0%B8%D0%BB%D1%8E%D1%87%D0%B8%D0%BD%D1%81%D0%BA%D0%BE%D0%B3%D0%BE_%D0%B2%D1%83%D0%BB%D0%BA%D0%B0%D0%BD%D0%B0.jpg",
    tags: ["landscape", "horizon"],
    whyGood:
      "狐狸雖小，卻放在中央偏左的三分交點上；前景草叢、中景岩石、遠景火山三層堆出空間感，晨光側照讓橘色毛皮從灰岩上分離出來。",
    principles: ["depth-layers", "rule-of-thirds", "golden-hour"],
  },
  {
    id: "img-people-animals-004",
    category: "people-animals",
    title: "雪地裡的紅狐",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Portrait_of_a_red_fox_in_Rautas_fj%C3%A4llurskog.jpg/960px-Portrait_of_a_red_fox_in_Rautas_fj%C3%A4llurskog.jpg",
    width: 5568,
    height: 3712,
    author: "ClaudiaTen",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Portrait_of_a_red_fox_in_Rautas_fj%C3%A4llurskog.jpg",
    tags: ["highkey", "minimal", "portrait"],
    whyGood:
      "整片雪地是天然的白色留白，橘紅毛色在高調畫面裡一眼被看見；狐狸偏右、視線朝鏡頭，左側留白給尾巴呼吸，曝光往右補正才保住雪的細節不死白。",
    principles: ["negative-space", "exposure", "color-harmony"],
  },
  {
    id: "img-people-animals-005",
    category: "people-animals",
    title: "鼻尖相觸的母狐與幼狐",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Arabian_Red_Fox_with_Juvenile.jpg/960px-Arabian_Red_Fox_with_Juvenile.jpg",
    width: 3000,
    height: 2212,
    author: "BirderSajan",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Arabian_Red_Fox_with_Juvenile.jpg",
    tags: ["portrait"],
    whyGood:
      "母狐低頭、幼狐仰頭鼻尖相觸的那一瞬，是等待才拍得到的畫面；淺景深把沙土背景化成同色系的柔和底色，兩張臉都落在清晰範圍內。",
    principles: ["moment", "depth-of-field", "color-harmony"],
  },
  {
    id: "img-people-animals-006",
    category: "people-animals",
    title: "銜著楓葉的梅花鹿",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/%D0%9E%D0%BB%D0%B5%D0%BD%D1%8C_%D0%B7_%D0%BA%D0%BB%D0%B5%D0%BD%D0%BE%D0%B2%D0%B8%D0%BC_%D0%BB%D0%B8%D1%81%D1%82%D0%BA%D0%BE%D0%BC.jpg/960px-%D0%9E%D0%BB%D0%B5%D0%BD%D1%8C_%D0%B7_%D0%BA%D0%BB%D0%B5%D0%BD%D0%BE%D0%B2%D0%B8%D0%BC_%D0%BB%D0%B8%D1%81%D1%82%D0%BA%D0%BE%D0%BC.jpg",
    width: 3000,
    height: 4500,
    author: "Byrdyak",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%D0%9E%D0%BB%D0%B5%D0%BD%D1%8C_%D0%B7_%D0%BA%D0%BB%D0%B5%D0%BD%D0%BE%D0%B2%D0%B8%D0%BC_%D0%BB%D0%B8%D1%81%D1%82%D0%BA%D0%BE%D0%BC.jpg",
    tags: ["portrait"],
    whyGood:
      "鹿嘴上那片黃葉是整張照片的重點，一抹亮色在灰褐色調裡跳出；直幅把鹿角完整收進畫面不切頂，背景樹枝虛化成灰色紋理不搶戲。",
    principles: ["moment", "subject-placement", "depth-of-field"],
  },
  {
    id: "img-people-animals-007",
    category: "people-animals",
    title: "黑夜裡的紅眼樹蛙",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Red-eyed_Tree_Frog_-_Litoria_chloris_edit1.jpg/960px-Red-eyed_Tree_Frog_-_Litoria_chloris_edit1.jpg",
    width: 1640,
    height: 1504,
    author: "LiquidGhoul edited by Muhammad",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Red-eyed_Tree_Frog_-_Litoria_chloris_edit1.jpg",
    tags: ["portrait", "lowkey", "centered"],
    whyGood:
      "黑背景把所有雜訊吃掉，只剩螢光綠的蛙身與橘色眼睛；正面置中構圖讓左右腳掌形成對稱，主體亮度控制得當，沒有因為閃燈直打而過曝。",
    principles: ["simplify", "exposure", "symmetry"],
  },
  {
    id: "img-people-animals-008",
    category: "people-animals",
    title: "草原上的雄獅正面像",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/011_The_lion_king_Tryggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg/960px-011_The_lion_king_Tryggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg",
    width: 2417,
    height: 3021,
    author: "Giles Laurent",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:011_The_lion_king_Tryggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg",
    tags: ["portrait"],
    whyGood:
      "眼睛落在畫面上三分之一處而不是正中央，鬃毛下方留出胸口與草叢；前後的乾草全部虛化，只有臉部銳利，正面直視帶來壓迫感。",
    principles: ["rule-of-thirds", "depth-of-field", "sharpness"],
  },
  {
    id: "img-people-animals-009",
    category: "people-animals",
    title: "閉目的雪猴",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Macaca_fuscata_meditation.jpg/960px-Macaca_fuscata_meditation.jpg",
    width: 5184,
    height: 3456,
    author: "Daisuke tashiro from Japan",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Macaca_fuscata_meditation.jpg",
    tags: ["portrait", "highkey", "centered", "symmetric"],
    whyGood:
      "貼近到只剩一張臉，雪地反光把背景與毛色一起推成高調的白，紅臉成為唯一色塊；左右對稱的正面構圖配上閉眼表情，安靜得像一張肖像畫。",
    principles: ["simplify", "symmetry", "exposure"],
  },
  {
    id: "img-people-animals-010",
    category: "people-animals",
    title: "冰面上的大藍鷺",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Great_blue_heron_in_GWC_%2821718%29.jpg/960px-Great_blue_heron_in_GWC_%2821718%29.jpg",
    width: 4758,
    height: 3456,
    author: "Rhododendrites",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Great_blue_heron_in_GWC_(21718).jpg",
    tags: ["lowkey", "minimal"],
    whyGood:
      "黃金時刻的低角度側光只打亮鷺鳥，暗色冰面成了天然黑背景；鳥朝左行走、頭部前方留出空間，長腿與冰上倒影構成穩定的三角形。",
    principles: ["golden-hour", "light-direction", "subject-placement"],
  },
  {
    id: "img-people-animals-011",
    category: "people-animals",
    title: "停在花穗上的豹紋蝶",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Balkan_fritillary_%28Boloria_graeca_balcanica%29_underside_Bulgaria.jpg/960px-Balkan_fritillary_%28Boloria_graeca_balcanica%29_underside_Bulgaria.jpg",
    width: 3781,
    height: 2520,
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Balkan_fritillary_(Boloria_graeca_balcanica)_underside_Bulgaria.jpg",
    tags: ["minimal", "portrait"],
    whyGood:
      "蝴蝶偏左停在三分線上，右側整片虛化的綠色留白讓翅膀紋路有地方呼吸；花穗從左下延伸上來當視線引導線，橘褐與綠是互補色。",
    principles: ["rule-of-thirds", "negative-space", "color-harmony"],
  },
  {
    id: "img-people-animals-012",
    category: "people-animals",
    title: "仰躺曬太陽的貓",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Sleeping_cat_on_her_back.jpg/960px-Sleeping_cat_on_her_back.jpg",
    width: 2304,
    height: 2304,
    author: "Umberto Salvagnin",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sleeping_cat_on_her_back.jpg",
    tags: ["portrait"],
    whyGood:
      "拍攝者站到貓的頭頂上方俯拍，讓四肢伸展的姿態變成有趣的放射線；正午硬光直射反而配合了慵懶主題，抓到閉眼張嘴伸懶腰的一瞬。",
    principles: ["perspective", "moment", "light-direction"],
  },
  {
    id: "img-people-animals-013",
    category: "people-animals",
    title: "藍眼睛的三色貓",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Tabby_cat_with_blue_eyes-3336579.jpg/960px-Tabby_cat_with_blue_eyes-3336579.jpg",
    width: 2877,
    height: 3456,
    author: "AdinaVoicu",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tabby_cat_with_blue_eyes-3336579.jpg",
    tags: ["portrait"],
    whyGood:
      "對焦準確落在那雙藍眼睛上，鬍鬚根根分明；背景在淺景深下化成一片暖橘，正好與藍眼睛形成冷暖對比，貓臉放在上半部、下方留出胸口。",
    principles: ["sharpness", "depth-of-field", "color-harmony"],
  },
  {
    id: "img-people-animals-014",
    category: "people-animals",
    title: "金色水面上的鴛鴦",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Aix_galericulata_%28Linnaeus_1758%29.jpg/960px-Aix_galericulata_%28Linnaeus_1758%29.jpg",
    width: 3226,
    height: 1626,
    author: "Michael Gäbler",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Aix_galericulata_(Linnaeus_1758).jpg",
    tags: ["minimal"],
    whyGood:
      "鴛鴦放在左側三分線，右邊大片金色倒影是刻意留下的留白；夕陽反射的黃色水面與鴛鴦的橘、藍、綠羽色形成濃郁卻和諧的配色。",
    principles: ["rule-of-thirds", "color-harmony", "golden-hour"],
  },
  {
    id: "img-people-animals-015",
    category: "people-animals",
    title: "懸停吸蜜的劍嘴蜂鳥",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Sword-billed_hummingbird_%28male%29_at_Guango_Lodge%2C_Ecuador_%2821310837273%29.jpg/960px-Sword-billed_hummingbird_%28male%29_at_Guango_Lodge%2C_Ecuador_%2821310837273%29.jpg",
    width: 4560,
    height: 3648,
    author: "Andy Morffew from Itchen Abbas, Hampshire, UK",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sword-billed_hummingbird_(male)_at_Guango_Lodge,_Ecuador_(21310837273).jpg",
    tags: ["minimal", "portrait"],
    whyGood:
      "花在左上、鳥在右下形成對角呼應，細長的嘴變成連接兩點的引導線；高速快門凝結翅膀，背景全部虛化成綠色，一滴花蜜正好落下。",
    principles: ["moment", "shutter-motion", "leading-lines"],
  },
  {
    id: "img-people-animals-016",
    category: "people-animals",
    title: "青苔枝上的輝蜂鳥",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Fawn-breasted_Brilliant_hummingbird_in_Ecuador_-_%2854564276957%29.jpg/960px-Fawn-breasted_Brilliant_hummingbird_in_Ecuador_-_%2854564276957%29.jpg",
    width: 3548,
    height: 2838,
    author: "Andy  Morffew from Itchen Abbas, Hampshire, UK",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fawn-breasted_Brilliant_hummingbird_in_Ecuador_-_(54564276957).jpg",
    tags: ["portrait", "minimal"],
    whyGood:
      "鳥站在右側三分線上，長滿青苔的枝條從左下斜上引到鳥腳；灰綠背景完全虛化，紅棕羽色與綠色頭部靠淺景深乾淨分離，眼睛銳利有神。",
    principles: ["rule-of-thirds", "leading-lines", "depth-of-field"],
  },
  {
    id: "img-people-animals-017",
    category: "people-animals",
    title: "仰望的黃金獵犬側臉",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/D%C3%BClmen%2C_Hausd%C3%BClmen%2C_Golden_Retriever_--_2022_--_5945.jpg/960px-D%C3%BClmen%2C_Hausd%C3%BClmen%2C_Golden_Retriever_--_2022_--_5945.jpg",
    width: 4364,
    height: 3273,
    author: "Dietmar Rabich",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:D%C3%BClmen,_Hausd%C3%BClmen,_Golden_Retriever_--_2022_--_5945.jpg",
    tags: ["portrait"],
    whyGood:
      "狗頭偏右、仰望的視線前方留白，側面輪廓完整不切耳；結霜的灌木背景被虛化成冷色調，反襯暖色毛髮，對焦落在眼睛與鼻頭。",
    principles: ["subject-placement", "depth-of-field", "color-harmony"],
  },
  {
    id: "img-people-animals-018",
    category: "people-animals",
    title: "晨光蘆葦間的天鵝",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/CygnusOlorNaturalHabitatMorning.jpg/960px-CygnusOlorNaturalHabitatMorning.jpg",
    width: 2585,
    height: 1688,
    author: "Thermos",
    license: "CC BY-SA 2.5",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.5",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:CygnusOlorNaturalHabitatMorning.jpg",
    tags: ["minimal"],
    whyGood:
      "日出低角度逆光把水面與蘆葦染成一片金色，白天鵝在逆光下仍保住羽毛細節；天鵝偏左下、落在蘆葦倒影的深色帶上，前方留出水面。",
    principles: ["golden-hour", "light-direction", "rule-of-thirds"],
  },
  {
    id: "img-people-animals-019",
    category: "people-animals",
    title: "天鵝頸部的曲線",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Mute_swan_%28Cygnus_olor%29_in_Bowness-on-Windermere%2C_England.jpg/960px-Mute_swan_%28Cygnus_olor%29_in_Bowness-on-Windermere%2C_England.jpg",
    width: 3500,
    height: 4700,
    author: "Michal Klajban",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mute_swan_(Cygnus_olor)_in_Bowness-on-Windermere,_England.jpg",
    tags: ["portrait", "minimal"],
    whyGood:
      "只取頭與頸，S形曲線從左下延伸到右上，把一隻常見的天鵝拍成線條練習；深藍水面被虛化成單色背景，白羽與橘嘴之外沒有其他顏色。",
    principles: ["simplify", "leading-lines", "color-harmony"],
  },
  {
    id: "img-people-animals-020",
    category: "people-animals",
    title: "沙灘上的非洲企鵝",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/African_penguin%2C_Cape_Town_%28_1050598%29.jpg/960px-African_penguin%2C_Cape_Town_%28_1050598%29.jpg",
    width: 1772,
    height: 2363,
    author: "Matti Blume",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:African_penguin,_Cape_Town_(_1050598).jpg",
    tags: ["minimal"],
    whyGood:
      "企鵝小小地站在沙灘下半部，上方大片沙面與岩壁是刻意的留白；正午硬光投下短影點出站姿。若把它放大置中，這份孤獨感就沒了。",
    principles: ["negative-space", "subject-placement", "light-direction"],
  },
  {
    id: "img-people-animals-021",
    category: "people-animals",
    title: "沙地上的三眼蜥蜴",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Three-eyed_lizard_%28Chalarodon_madagascariensis%29_male_Toliara.jpg/960px-Three-eyed_lizard_%28Chalarodon_madagascariensis%29_male_Toliara.jpg",
    width: 5175,
    height: 3450,
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Three-eyed_lizard_(Chalarodon_madagascariensis)_male_Toliara.jpg",
    tags: ["minimal"],
    whyGood:
      "蜥蜴身體在左，尾巴畫一道大弧線甩到右邊，成為畫面本身的引導線；沙地前後全部虛化只剩主體清晰，米色底上的橘褐斑紋靠低對比襯出質感。",
    principles: ["leading-lines", "depth-of-field", "simplify"],
  },
  {
    id: "img-people-animals-022",
    category: "people-animals",
    title: "浮出水面的環斑海豹",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/%D0%9D%D0%B5%D1%80%D0%BF%D0%B8%D1%87%D0%B8%D0%B9_%D0%B2%D0%B7%D0%B3%D0%BB%D1%8F%D0%B4.jpg/960px-%D0%9D%D0%B5%D1%80%D0%BF%D0%B8%D1%87%D0%B8%D0%B9_%D0%B2%D0%B7%D0%B3%D0%BB%D1%8F%D0%B4.jpg",
    width: 4114,
    height: 2743,
    author: "Кирилл Уютнов",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%D0%9D%D0%B5%D1%80%D0%BF%D0%B8%D1%87%D0%B8%D0%B9_%D0%B2%D0%B7%D0%B3%D0%BB%D1%8F%D0%B4.jpg",
    tags: ["minimal"],
    whyGood:
      "海豹頭部放在右下三分交點，左側留出它游過來的水波與大片藍色留白；水面倒影補成第二張臉，正對鏡頭的眼神是耐心等待換來的瞬間。",
    principles: ["rule-of-thirds", "negative-space", "moment"],
  },
  {
    id: "img-still-life-001",
    category: "still-life",
    title: "燈下熱騰騰的麵包",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Pinoy_Pandesal.jpg/960px-Pinoy_Pandesal.jpg",
    width: 5472,
    height: 3648,
    author: "Jessartcam",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pinoy_Pandesal.jpg",
    tags: ["food", "lowkey"],
    whyGood:
      "煤油燈暖光從右後方逆打，蒸氣被光勾出輪廓；藍色布巾與黃色紗巾是互補色，麵包放在中央偏下，咖啡杯與燈退到虛化的背景，形成前中後三層。",
    principles: ["light-direction", "color-harmony", "depth-layers"],
  },
  {
    id: "img-still-life-002",
    category: "still-life",
    title: "透光的柑橘切片",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Citrus_fruits.jpg/960px-Citrus_fruits.jpg",
    width: 2700,
    height: 1779,
    author: "Scott Bauer, USDA",
    license: "Public domain",
    licenseUrl: "https://commons.wikimedia.org/wiki/Commons:Licensing",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Citrus_fruits.jpg",
    tags: ["food", "highkey", "busy"],
    whyGood:
      "從下方打光讓每片柑橘像彩色玻璃，果肉紋理全靠透光呈現；填滿整個畫面的重複圓形是圖案式構圖，白底高調，只用橘、黃、綠三色。",
    principles: ["light-direction", "symmetry", "color-harmony"],
  },
  {
    id: "img-still-life-003",
    category: "still-life",
    title: "一排四顆洋梨",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Four_pears.jpg/960px-Four_pears.jpg",
    width: 4426,
    height: 2080,
    author: "Rhododendrites",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Four_pears.jpg",
    tags: ["food", "minimal", "highkey"],
    whyGood:
      "四顆梨排成一列，顏色由黃到深紅漸層，把「重複與變化」放在同一張裡；灰白無縫背景拍成極簡靜物，柔光讓果皮質感清楚又不出現硬陰影。",
    principles: ["simplify", "color-harmony", "light-direction"],
  },
  {
    id: "img-still-life-004",
    category: "still-life",
    title: "黑底上的柿子",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Fuyu_persimmon_fruits%2C_one_cut_open.jpg/960px-Fuyu_persimmon_fruits%2C_one_cut_open.jpg",
    width: 5472,
    height: 3648,
    author: "Frank Schulenburg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fuyu_persimmon_fruits,_one_cut_open.jpg",
    tags: ["food", "lowkey"],
    whyGood:
      "黑色壓克力板同時當背景與倒影面，橘色柿子在低調畫面裡格外飽滿；一顆完整一顆切半，左右並排互相呼應，柔光從側面帶出果皮光澤。",
    principles: ["simplify", "light-direction", "color-harmony"],
  },
  {
    id: "img-still-life-005",
    category: "still-life",
    title: "懸垂的野草莓",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Fragaria_vesca_fruit_-_Keila.jpg/960px-Fragaria_vesca_fruit_-_Keila.jpg",
    width: 4000,
    height: 5600,
    author: "Ivar Leidus",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fragaria_vesca_fruit_-_Keila.jpg",
    tags: ["food", "minimal"],
    whyGood:
      "一顆野草莓掛在直幅下半部，莖從上方彎進來當引導線；橄欖綠純色背景與紅果是互補色，大片留白讓小果實顯得珍貴，籤粒顆顆銳利。",
    principles: ["negative-space", "color-harmony", "sharpness"],
  },
  {
    id: "img-still-life-006",
    category: "still-life",
    title: "復活節早餐俯拍",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Easter_breakfast_in_Serbia_%28close-up%29.jpg/960px-Easter_breakfast_in_Serbia_%28close-up%29.jpg",
    width: 5184,
    height: 3888,
    author: "Petar Milošević",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Easter_breakfast_in_Serbia_(close-up).jpg",
    tags: ["food", "busy"],
    whyGood:
      "正上方俯拍讓桌面變成平面構圖，紅絲絨桌布統一了整張的底色；主盤放中央，四角各擺一碟形成穩定平衡，黃蛋與青蔥在紅底上跳出來。",
    principles: ["perspective", "color-harmony", "subject-placement"],
  },
  {
    id: "img-still-life-007",
    category: "still-life",
    title: "紙緣的光影",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Papierkanten_--_2020_--_9535.jpg/960px-Papierkanten_--_2020_--_9535.jpg",
    width: 5973,
    height: 4480,
    author: "Dietmar Rabich",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Papierkanten_--_2020_--_9535.jpg",
    tags: ["minimal", "lowkey"],
    whyGood:
      "只是幾張捲起的紙，靠一盞側光就變成抽象作品；青綠單色配黑色陰影，亮面與暗面的對比本身就是主題，證明簡化到極致也能成立。",
    principles: ["simplify", "light-direction", "color-harmony"],
  },
  {
    id: "img-still-life-008",
    category: "still-life",
    title: "螺絲排成的城市天際線",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Sechskantschrauben_--_2020_--_3985-8.jpg/960px-Sechskantschrauben_--_2020_--_3985-8.jpg",
    width: 6558,
    height: 4367,
    author: "Dietmar Rabich",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sechskantschrauben_--_2020_--_3985-8.jpg",
    tags: ["symmetric", "minimal", "centered"],
    whyGood:
      "螺絲排成高低起伏的天際線，鏡面反射做出完美的上下對稱，主體置中在這裡反而是對的；深藍純色背景與金屬色只有兩種顏色，水平線筆直對稱才成立。",
    principles: ["symmetry", "horizon-level", "simplify"],
  },
  {
    id: "img-still-life-009",
    category: "still-life",
    title: "黑白棋兵",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Schachfiguren%2C_Bauern_--_2022_--_0022_%28bw%29.jpg/960px-Schachfiguren%2C_Bauern_--_2022_--_0022_%28bw%29.jpg",
    width: 6720,
    height: 4480,
    author: "Dietmar Rabich",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Schachfiguren,_Bauern_--_2022_--_0022_(bw).jpg",
    tags: ["bw", "minimal"],
    whyGood:
      "唯一的黑兵放在右側三分處，一排白兵斜向後退形成引導線；黑白處理去掉木紋色彩後只剩明暗與形狀，淺景深讓前後的兵逐漸模糊。",
    principles: ["rule-of-thirds", "leading-lines", "depth-of-field"],
  },
  {
    id: "img-still-life-010",
    category: "still-life",
    title: "青苔上的懷錶",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/D%C3%BClmen%2C_Kirchspiel%2C_ehem._Sondermunitionslager_Visbeck%2C_%22What_if%22_--_2023_--_6686_%28kreativ_2%29.jpg/960px-D%C3%BClmen%2C_Kirchspiel%2C_ehem._Sondermunitionslager_Visbeck%2C_%22What_if%22_--_2023_--_6686_%28kreativ_2%29.jpg",
    width: 4318,
    height: 4318,
    author: "Dietmar Rabich",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:D%C3%BClmen,_Kirchspiel,_ehem._Sondermunitionslager_Visbeck,_%22What_if%22_--_2023_--_6686_(kreativ_2).jpg",
    tags: ["lowkey", "centered"],
    whyGood:
      "懷錶置中放在貼地的低視角，前景草絮與背景光斑都虛化，只有錶面清楚；冷藍單色調營造時間停止的氛圍，圓形光斑與圓形錶殼互相呼應。",
    principles: ["depth-of-field", "color-harmony", "perspective"],
  },
  {
    id: "img-still-life-011",
    category: "still-life",
    title: "白盤上的巧克力蛋糕",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Piece_of_chocolate_cake_on_a_white_plate_decorated_with_chocolate_sauce.jpg/960px-Piece_of_chocolate_cake_on_a_white_plate_decorated_with_chocolate_sauce.jpg",
    width: 5536,
    height: 3766,
    author: "Daria YakovlevaMinor edits made by Subsidiary account",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Piece_of_chocolate_cake_on_a_white_plate_decorated_with_chocolate_sauce.jpg",
    tags: ["food", "highkey"],
    whyGood:
      "白盤白桌的高調畫面裡，蛋糕的褐色層次成為唯一重點；巧克力醬線條與可可粉不只是裝飾，還是把視線導向蛋糕的引導線，柔光讓白盤不過曝。",
    principles: ["simplify", "leading-lines", "exposure"],
  },
  {
    id: "img-still-life-012",
    category: "still-life",
    title: "生魚片的色帶",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Sashimi_of_S%C3%A3o_Paulo.jpg/960px-Sashimi_of_S%C3%A3o_Paulo.jpg",
    width: 4288,
    height: 2848,
    author: "Wilfredor",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sashimi_of_S%C3%A3o_Paulo.jpg",
    tags: ["food", "busy"],
    whyGood:
      "三種魚肉排成三條斜向色帶，紅、橘、白由上而下漸層，填滿畫面的重複片狀是圖案式構圖；貼近拍讓魚肉紋理與油脂光澤成為主角。",
    principles: ["symmetry", "color-harmony", "simplify"],
  },
  {
    id: "img-still-life-013",
    category: "still-life",
    title: "帶露珠的玫瑰花苞",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Englische_Rose_The_Reeve_Tropfen_-RM-20190821-01.jpg/960px-Englische_Rose_The_Reeve_Tropfen_-RM-20190821-01.jpg",
    width: 3837,
    height: 4708,
    author: "Ermell",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Englische_Rose_The_Reeve_Tropfen_-RM-20190821-01.jpg",
    tags: ["minimal"],
    whyGood:
      "花苞放在直幅的上三分之一，花莖與蜘蛛絲從下方延伸上來；深綠背景被淺景深化成柔和色塊，粉紅在互補的綠色前跳出，水珠顆顆清晰。",
    principles: ["rule-of-thirds", "depth-of-field", "color-harmony"],
  },
  {
    id: "img-still-life-014",
    category: "still-life",
    title: "沾滿霜露的紅菊",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Chrysantheme_rot_tautropfen_-20191024-RM-102058.jpg/960px-Chrysantheme_rot_tautropfen_-20191024-RM-102058.jpg",
    width: 5212,
    height: 3908,
    author: "Ermell",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chrysantheme_rot_tautropfen_-20191024-RM-102058.jpg",
    tags: ["minimal"],
    whyGood:
      "花朝右側傾斜，花瓣前端留有空間不貼邊；灰綠色的虛化背景把紅色襯得更飽和，微距對焦鎖在前排露珠，後排花瓣自然柔化形成層次。",
    principles: ["depth-of-field", "subject-placement", "color-harmony"],
  },
  {
    id: "img-still-life-015",
    category: "still-life",
    title: "深藍背景的黃鬱金香花苞",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Bostulp_%28Tulipa_sylvestris%29%2C_zwellende_bloemknop._24-03-2022_%28d.j.b.%29_01.jpg/960px-Bostulp_%28Tulipa_sylvestris%29%2C_zwellende_bloemknop._24-03-2022_%28d.j.b.%29_01.jpg",
    width: 4806,
    height: 3004,
    author: "Dominicus Johannes Bergsma",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bostulp_(Tulipa_sylvestris),_zwellende_bloemknop._24-03-2022_(d.j.b.)_01.jpg",
    tags: ["minimal"],
    whyGood:
      "花莖從右上伸進畫面，花苞尖端指向左下，一條對角線就撐起整張；深藍背景與黃色是強烈互補色，畫面只有兩色，沒有一根多餘的葉子。",
    principles: ["leading-lines", "color-harmony", "simplify"],
  },
  {
    id: "img-still-life-016",
    category: "still-life",
    title: "彈起的水滴",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Water_drop_001.jpg/960px-Water_drop_001.jpg",
    width: 3714,
    height: 2475,
    author: "José Manuel Suárez from Spain",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Water_drop_001.jpg",
    tags: ["minimal"],
    whyGood:
      "高速快門凝結水滴彈起的一刻，水柱與水滴排成一條垂直線置中；藍白布景透過水面折射變成流動的色塊，前後全虛化，只有水滴與水柱清晰。",
    principles: ["shutter-motion", "moment", "depth-of-field"],
  },
  {
    id: "img-still-life-017",
    category: "still-life",
    title: "陽光下的藍綠玻璃瓶",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Colorful_bottle.jpg/960px-Colorful_bottle.jpg",
    width: 2272,
    height: 1704,
    author: "Matthew Bowden www.digitallyrefreshing.com",
    license: "Attribution",
    licenseUrl: "https://commons.wikimedia.org/wiki/Commons:Licensing",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Colorful_bottle.jpg",
    tags: ["highkey", "minimal"],
    whyGood:
      "直射陽光穿過玻璃，把藍綠色投影在白桌上，影子成了第二個主體；純白背景的高調處理讓畫面只剩一種顏色，瓶口與影子都朝左下延伸成對角線。",
    principles: ["light-direction", "color-harmony", "simplify"],
  },
  {
    id: "img-still-life-018",
    category: "still-life",
    title: "黑底上的黃色小番茄",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Yellow_cherry_tomatoes.jpg/960px-Yellow_cherry_tomatoes.jpg",
    width: 6000,
    height: 4000,
    author: "Ivar Leidus",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Yellow_cherry_tomatoes.jpg",
    tags: ["food", "lowkey"],
    whyGood:
      "黑色霧面底板吸掉所有雜訊，三顆黃番茄成為唯一亮部；切半那顆放在前方中央、兩顆完整的退到後面形成三角形，側光讓果皮出現高光與圓潤感。",
    principles: ["simplify", "light-direction", "subject-placement"],
  },
  {
    id: "img-still-life-019",
    category: "still-life",
    title: "甜椒裡長出的小甜椒",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/IleBaby_Bell_pepper_Capsicum_annuum_2.jpg/960px-IleBaby_Bell_pepper_Capsicum_annuum_2.jpg",
    width: 1848,
    height: 1700,
    author: "Brocken Inaglory",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:IleBaby_Bell_pepper_Capsicum_annuum_2.jpg",
    tags: ["lowkey", "centered"],
    whyGood:
      "黑背景讓剖開甜椒裡長出的小甜椒像雕塑一樣獨立出來，主體置中、彎曲的蒂頭上方留有空間；綠與橘紅只有兩色，直幅完整收進整個形體。",
    principles: ["simplify", "subject-placement", "color-harmony"],
  },
  {
    id: "img-still-life-020",
    category: "still-life",
    title: "水中的紅黃辣椒",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Peppers_in_water.jpg/960px-Peppers_in_water.jpg",
    width: 5984,
    height: 2920,
    author: "ulleo",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Peppers_in_water.jpg",
    tags: ["food", "lowkey"],
    whyGood:
      "辣椒沉在水中，附著的氣泡讓表面有了質感，黑底把紅黃兩色推到最飽和卻不顯塑膠感；兩根辣椒彎成相反方向的弧線互相呼應，橫幅左右留出氣泡空間。",
    principles: ["simplify", "color-harmony", "saturation"],
  },
  {
    id: "img-still-life-021",
    category: "still-life",
    title: "甩出杯口的紅酒",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Schwappender_Wein.jpg/960px-Schwappender_Wein.jpg",
    width: 2608,
    height: 3920,
    author: "Stefan Krause, Germany",
    license: "CC BY 3.0 de",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/de/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Schwappender_Wein.jpg",
    tags: ["food", "lowkey"],
    whyGood:
      "紅酒甩出杯口的一瞬靠高速快門凝結，酒的S形曲線是畫面主線；棕色漸層背景與木桌統一成暖色調，酒杯在左、酒瓶在右、麵包起司墊在下方形成三角構圖。",
    principles: ["shutter-motion", "moment", "color-harmony"],
  },
  {
    id: "img-still-life-022",
    category: "still-life",
    title: "高調的白蛋",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/001_2022_04_09_Ei.jpg/960px-001_2022_04_09_Ei.jpg",
    width: 3630,
    height: 5861,
    author: "Friedrich Haag",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:001_2022_04_09_Ei.jpg",
    tags: ["highkey", "minimal", "centered", "symmetric"],
    whyGood:
      "白蛋、白蛋杯、白背景，全靠曝光補償往右推才不會拍成灰；置中對稱的構圖配合極簡主題，只剩形狀與微弱的陰影，是高調攝影的教科書範例。",
    principles: ["exposure", "symmetry", "simplify"],
  },
  {
    id: "img-still-life-023",
    category: "still-life",
    title: "五彩的觀賞辣椒",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Capsicum_annuum_var._Fiesta_-_MHNT.jpg/960px-Capsicum_annuum_var._Fiesta_-_MHNT.jpg",
    width: 3456,
    height: 4608,
    author: "PierreSelim",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Capsicum_annuum_var._Fiesta_-_MHNT.jpg",
    tags: ["food", "busy"],
    whyGood:
      "紅橙黃的辣椒全朝上生長，在互補的綠葉前像一把火；直幅讓長條形的辣椒有伸展空間，草地背景被淺景深化成純綠色塊，元素雖多，顏色只有紅與綠兩組。",
    principles: ["color-harmony", "depth-of-field", "simplify"],
  },
  {
    id: "img-still-life-024",
    category: "still-life",
    title: "雨中的白色扶桑花",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Waterdrops_White_Hibiscus_Inakanahalli_Coorg_Jun24_A7CR_01657.jpg/960px-Waterdrops_White_Hibiscus_Inakanahalli_Coorg_Jun24_A7CR_01657.jpg",
    width: 3930,
    height: 5240,
    author: "Timothy A. Gonsalves",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Waterdrops_White_Hibiscus_Inakanahalli_Coorg_Jun24_A7CR_01657.jpg",
    tags: ["minimal"],
    whyGood:
      "花朵垂掛在直幅中央偏上，橘紅花蕊往下延伸把視線帶到底部；深綠背景被淺景深化成柔和色塊，白花在陰天柔光下保住水珠細節，雨絲成了額外的線條。",
    principles: ["depth-of-field", "golden-hour", "leading-lines"],
  },
]
