// 每日拍照任務 deck（60 題）。
// 欄位語意與字數範圍見 types.ts 的 Challenge；principles 只准用 principles.ts 的 id。
import type { Challenge } from './types'

export const CHALLENGES: Challenge[] = [
  {
    id: 'ch-frame-in-frame',
    title: '框中框',
    brief: '找一個現成的框——門框、窗框、鏡子邊、書架的格子——把主體放進框裡拍。判斷標準：遮住框以後，主體是不是變得沒那麼吸引人？有，就代表框有在幫你。',
    tips: ['框要完整入鏡，四邊都留一點邊，不要只露出一半。', '主體別貼著框邊，放在框內偏一側更自然。', '框本身可以稍微暗一點，視線才會往裡面走。'],
    principles: ['framing'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-one-color',
    title: '一種顏色',
    brief: '整張照片只准出現一種主色和它的深淺變化，例如全綠的盆栽角落、全白的床單和杯子。判斷標準：把照片縮到很小，還能一眼說出「這是一張綠色的照片」。',
    tips: ['先鎖定顏色再找主體，不要反過來。', '小面積的雜色用手移開，或換個角度擋掉。', '後製稍微降飽和度，單色會更有質感。'],
    principles: ['color-harmony', 'simplify'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-shadow-hero',
    title: '影子當主角',
    brief: '拍一張「影子比本尊重要」的照片：欄杆的影子、人的影子、腳踏車的影子。本尊可以只露一點或完全不入鏡。判斷標準：遮住影子，照片就沒東西看了。',
    tips: ['上午十點前或下午三點後，影子才夠長夠清楚。', '對著影子點一下對焦，讓影子區域曝光正常、別死黑。', '乾淨的地面（水泥、磁磚）比草地更能襯出影子。'],
    principles: ['light-direction', 'simplify'],
    difficulty: 2,
    indoorOk: false,
  },
  {
    id: 'ch-partial-only',
    title: '只拍局部',
    brief: '選一個熟悉的物件或一個人，故意只拍其中一小塊：鞋子和地板、握著杯子的手、貓的半張臉。判斷標準：看的人猜得到那是什麼，但畫面裡並沒有完整的它。',
    tips: ['切的位置要果斷，切在關節、邊緣的一半會顯得像失誤。', '靠近拍，讓局部填滿畫面三分之二以上。', '留下的那一塊要有細節或質感，才撐得起整張。'],
    principles: ['simplify', 'subject-placement'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-puddle-mirror',
    title: '水窪倒影',
    brief: '雨後找一個水窪，把手機貼近水面往上拍，讓建築、招牌或人出現在倒影裡。判斷標準：倒影占畫面至少一半，而且能認出倒影裡是什麼。',
    tips: ['手機翻過來、鏡頭朝下貼近水面，倒影會大很多。', '把手機上下顛倒看一次，好的倒影照倒過來也成立。', '等水面靜止再按，風一吹倒影就散了。'],
    principles: ['symmetry', 'perspective'],
    difficulty: 2,
    indoorOk: false,
  },
  {
    id: 'ch-three-elements',
    title: '極簡三元素',
    brief: '畫面裡最多只能有三樣東西，例如一張桌、一杯咖啡、一道光。判斷標準：數一數照片裡能被叫出名字的東西，超過三個就重拍或移走。',
    tips: ['先清空桌面或找一面空牆當背景，再一樣一樣放回去。', '三樣東西大小要有差別，一大一中一小最好看。', '拍完想一想：拿掉其中一樣還成立嗎？成立就再拿掉。'],
    principles: ['simplify', 'negative-space'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-backlight-silhouette',
    title: '逆光剪影',
    brief: '傍晚面對夕陽或亮的天空，讓人或樹整個變成黑色輪廓。判斷標準：主體是全黑的，但從外型一眼認得出是什麼；天空的顏色還在，沒有變成一片白。',
    tips: ['對焦點點在亮的天空上，主體就會自動變黑。', '請對方站到側面，側臉輪廓比正面的黑塊好認。', '主體背後要乾淨，剪影疊在建築上會糊成一團。'],
    principles: ['light-direction', 'exposure'],
    difficulty: 2,
    indoorOk: false,
  },
  {
    id: 'ch-window-side-light',
    title: '窗邊側光人像',
    brief: '關掉室內燈，請對方側身坐在窗邊，只用窗外的光拍一張半身照。判斷標準：臉的一側亮、一側暗，鼻子在暗面留下一道影子，臉是立體的不是平的。',
    tips: ['對方離窗約一步，太近會太亮，太遠對比會不夠。', '陰天的窗光最柔，直射太陽可拉一層薄窗簾。', '暗面太黑就在另一側放一張白紙或白色枕頭反光。'],
    principles: ['light-direction', 'depth-of-field'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-blue-hour',
    title: '藍調時刻',
    brief: '日落後約二十到四十分鐘，天空是深藍色、路燈和招牌剛亮起，出門拍一張街景。判斷標準：天空有藍色而不是黑色，燈光是暖黃的，兩種顏色同時存在。',
    tips: ['先查日落時間，提早十分鐘到定點，藍調只有二十分鐘左右。', '不要開夜景模式太早，天空還有藍時一般模式就夠。', '白平衡別讓手機自動修掉藍色，鎖定後手動調偏暖一點。'],
    principles: ['golden-hour', 'white-balance'],
    difficulty: 2,
    indoorOk: false,
  },
  {
    id: 'ch-streetlamp-portrait',
    title: '路燈下的人',
    brief: '夜裡找一盞路燈，請對方站在燈正下方偏前一點，拍一張只靠路燈打光的人像。判斷標準：臉上看得到光、看得到眼睛，背景是暗的但沒有整片顆粒。',
    tips: ['對方稍微抬頭，頂光才不會把眼窩壓成兩個黑洞。', '對焦點點在臉上並鎖定，手機才不會被亮燈騙去減曝。', '開夜景模式並手肘夾緊，或靠著燈桿穩住。'],
    principles: ['noise', 'light-direction'],
    difficulty: 3,
    indoorOk: false,
  },
  {
    id: 'ch-light-trail',
    title: '車燈拖影',
    brief: '晚上到天橋或路口，把手機靠在欄杆上，拍出車燈拉成紅色和白色的線。判斷標準：車身消失、只剩光的線條，而且建築物和路面是清楚的。',
    tips: ['用長曝光或夜景模式的手動秒數，先從三秒開始試。', '手機一定要靠著東西，用耳機線或倒數計時按快門。', '車流間隔長就多拍幾張，選線條最滿的一張。'],
    principles: ['shutter-motion', 'noise'],
    difficulty: 3,
    indoorOk: false,
  },
  {
    id: 'ch-freeze-drop',
    title: '凝結水滴',
    brief: '在水龍頭或水杯上方，拍下水滴落下、水花濺起的那一瞬。判斷標準：水滴或水花的邊緣是清楚的，看得出形狀，而不是一條模糊的水線。',
    tips: ['把場景搬到窗邊或檯燈下，光越亮快門越快越不糊。', '用連拍模式按住不放，再從裡面挑一張。', '先對焦在水滴會經過的位置，鎖定對焦再開始滴。'],
    principles: ['shutter-motion', 'sharpness'],
    difficulty: 2,
    indoorOk: true,
  },
  {
    id: 'ch-ground-level',
    title: '貼地視角',
    brief: '把手機放到幾乎碰到地面的高度，拍一張平常不會看到的畫面：桌腳下的貓、地磚延伸到門口、公園草皮的高度。判斷標準：畫面下半是地面，而且能感覺出「我也在地上」。',
    tips: ['手機倒過來拿，鏡頭在下面才能真的貼地。', '用螢幕預覽、不必趴著看，先按再檢查。', '地面上有一點小東西在前景，畫面會更有空間感。'],
    principles: ['perspective'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-wait-for-light',
    title: '等人走進光裡',
    brief: '找一塊落在地上或牆上的光斑（巷口的陽光、騎樓的一道光），架好構圖，等一個路人走進光斑的那一刻按下快門。判斷標準：人正好在光裡，身體是亮的，周圍是暗的。',
    tips: ['先對好焦、決定好構圖，接下來只等人，不要再挪手機。', '看到有人朝光走過來就開連拍，不要等他踏進去才按。', '一個人比一群人好，畫面裡最亮的地方只留給一個人。'],
    principles: ['moment', 'light-direction'],
    difficulty: 3,
    indoorOk: false,
  },
  {
    id: 'ch-thirds-cup',
    title: '杯子放三分點',
    brief: '打開相機的九宮格線，把桌上的一個杯子拍三次：正中央、左邊交叉點、右邊交叉點。判斷標準：三張並排，你能說出偏一側的那張為什麼比正中央的好看（或哪種情境下不會）。',
    tips: ['相機設定裡把「格線」打開，交叉點就是三分點。', '杯子偏左，右邊留空；杯把朝哪一邊，就往反方向留空間。', '背景保持乾淨，這題練的是位置，不是道具。'],
    principles: ['rule-of-thirds'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-corridor-lines',
    title: '走廊盡頭',
    brief: '站在家裡或辦公室走廊的一端，讓兩側牆線、地板接縫一起往盡頭匯聚。判斷標準：視線會不自覺被拉到畫面深處，盡頭放一個人或一扇門會更好。',
    tips: ['站在走廊正中央、手機舉到胸口高度，兩邊線條才會對稱。', '手機拿正，垂直線一歪整條走廊就像要倒。', '盡頭如果有光或窗，等它最亮的時候拍。'],
    principles: ['leading-lines'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-sky-space',
    title: '大片天空留白',
    brief: '出門找一個小小的主體——一隻鳥、一根電線桿頂、一個人的背影——讓它占畫面不到十分之一，其餘都給乾淨的天空。判斷標準：主體很小卻是第一眼看到的東西。',
    tips: ['把主體放在下方三分線附近，而不是正中央。', '陰天的灰白天空也算留白，不一定要藍天。', '構圖時檢查天空裡有沒有多餘電線，有就挪一步避開。'],
    principles: ['negative-space', 'subject-placement'],
    difficulty: 2,
    indoorOk: false,
  },
  {
    id: 'ch-river-horizon',
    title: '河濱水平線',
    brief: '到河濱或海邊，把對岸或海平面拍成一條真正水平的線。判斷標準：把照片放進編輯器的裁切，網格線和水平線完全重疊，不必再轉。',
    tips: ['相機設定裡開「水平儀」或「格線」，看到準了再按。', '水平線放在上三分線或下三分線，不要正中間切一半。', '拍完用編輯的「旋轉」微調，能校正就代表原本歪了，下次拍就更注意。'],
    principles: ['horizon-level'],
    difficulty: 2,
    indoorOk: false,
  },
  {
    id: 'ch-desk-flatlay',
    title: '俯拍桌面',
    brief: '把手機舉到桌面正上方、鏡頭完全朝下，拍一張早餐或工作桌的俯視照。判斷標準：桌面沒有變形成梯形，每樣東西的邊緣都是直的。',
    tips: ['手機拿平，用水平儀對到兩個十字重疊。', '東西之間要留空隙，不要疊在一起。', '光從側邊窗戶來最好，自己的影子別壓到桌面。'],
    principles: ['perspective', 'simplify'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-leaf-foreground',
    title: '借一片葉當前景',
    brief: '在公園或路邊，讓一片葉子、一根樹枝離鏡頭很近並且失焦，主體在中景。判斷標準：前景是模糊的一團綠或一團色，主體清楚，畫面有「透過什麼在看」的感覺。',
    tips: ['前景離鏡頭十公分內，才會夠模糊。', '點一下主體對焦，別讓手機對到前景。', '前景只占畫面一角或一邊，蓋住一半以上就搶戲了。'],
    principles: ['depth-layers'],
    difficulty: 2,
    indoorOk: false,
  },
  {
    id: 'ch-golden-profile',
    title: '黃金時刻側臉',
    brief: '日落前一小時，請對方側身站著，讓低角度的陽光從側前方打在臉上，拍一張暖色調人像。判斷標準：皮膚是金黃色的，眼睛裡有光點，影子長而柔。',
    tips: ['查日落時間，提前一小時到定點才不會錯過。', '請對方微微轉向太陽，鼻影短一點會比較好看。', '白平衡別讓手機修正成白光，暖色就是這題的重點。'],
    principles: ['golden-hour', 'light-direction'],
    difficulty: 2,
    indoorOk: false,
  },
  {
    id: 'ch-bokeh-lights',
    title: '遠處燈變光點',
    brief: '晚上把一個近的主體（手中的飲料、路邊的花）放在鏡頭前，讓後方的路燈和招牌變成圓圓的光斑。判斷標準：主體清楚，背景的燈是一顆顆模糊的圓球而不是光源本身。',
    tips: ['主體離鏡頭近、背景燈離主體遠，兩段距離差越大越好。', '開人像模式，把模糊強度調高一點。', '背景要有多顆燈才熱鬧，一顆燈的光斑很孤單。'],
    principles: ['depth-of-field', 'noise'],
    difficulty: 2,
    indoorOk: false,
  },
  {
    id: 'ch-window-hdr',
    title: '窗內窗外都清楚',
    brief: '白天站在室內，同時拍到窗邊的物件和窗外的景色。判斷標準：窗外沒有白成一片，室內物件也沒有黑成剪影，兩邊都看得到細節。',
    tips: ['把 HDR 或「智慧 HDR」打開，這正是它的用途。', '對焦點點在窗外和室內的交界，讓手機兩邊都顧到。', '拍完看直方圖，左右兩端都不要頂到邊。'],
    principles: ['dynamic-range', 'exposure'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-white-paper',
    title: '白紙拍成白',
    brief: '在家裡三個不同的光源下（窗邊、黃燈下、白色日光燈下）各拍一張白紙。判斷標準：三張的白紙都是白的，沒有一張偏黃或偏藍；不行就用編輯的白平衡拉回來。',
    tips: ['先看白紙旁邊有沒有其他顏色的東西反光影響。', '編輯時調「色溫」滑桿，往藍推能救偏黃，往黃推能救偏藍。', '同一張照片裡有兩種燈就先關一種，混光最難救。'],
    principles: ['white-balance'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-desaturate',
    title: '減飽和',
    brief: '找一張你之前拍過、覺得顏色太鮮的照片，把飽和度往下降，找到「還有顏色但不刺眼」的那個點。判斷標準：把原圖和修過的並排，修過的那張皮膚或天空看起來比較真實。',
    tips: ['飽和度降到覺得太淡，再往回加一點，通常就是對的。', '「鮮豔度」比「飽和度」溫和，先動鮮豔度。', '原本紅色、橘色最容易爆，特別留意這兩色。'],
    principles: ['saturation'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-eye-focus',
    title: '對焦在眼睛',
    brief: '幫人或寵物拍一張半身照，對焦點點在離鏡頭較近的那隻眼睛上。判斷標準：放大到最大看，睫毛或眼線是清楚的，耳朵和背景可以模糊。',
    tips: ['先點螢幕上的眼睛，再半按或等黃框出現才按快門。', '對方稍微偏頭，讓一隻眼睛比另一隻近，畫面會有立體感。', '距離半公尺以上再用人像模式，太近會對不到。'],
    principles: ['sharpness', 'depth-of-field'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-night-mode-corner',
    title: '夜景模式街角',
    brief: '晚上找一個有招牌、有路燈的街角，先用一般模式拍，再用夜景模式拍同一張。判斷標準：夜景模式那張暗處看得到細節而且顆粒少，招牌也沒變成一團白光。',
    tips: ['手肘夾緊、靠牆或靠桿，夜景模式要撐住幾秒。', '畫面裡有一盞很亮的燈時，點它一下讓手機降曝，招牌才不會過曝。', '兩張並排比較，看暗處的牆面顆粒差多少。'],
    principles: ['noise', 'exposure'],
    difficulty: 2,
    indoorOk: false,
  },
  {
    id: 'ch-pet-turn',
    title: '寵物回頭那一瞬',
    brief: '拍一張寵物聽到聲音回頭看鏡頭的瞬間。判斷標準：眼睛清楚、正在看鏡頭，耳朵有動作，不是趴著呆坐的平常照。',
    tips: ['先對焦、構好圖，再用零食袋或彈舌聲叫它。', '開連拍模式，聲音一出就按住快門不放。', '蹲到和它眼睛同高，回頭的視線才會落進鏡頭裡。'],
    principles: ['moment', 'sharpness'],
    difficulty: 2,
    indoorOk: true,
  },
  {
    id: 'ch-repeat-pattern',
    title: '重複圖案',
    brief: '找一個重複的東西填滿整張照片：磁磚、一排杯子、書櫃的書背、樓梯的階。判斷標準：畫面裡沒有主體，只有節奏；如果有一格特別不同，那就是視覺焦點。',
    tips: ['正對著圖案拍，稍微歪一點重複感就散掉。', '讓圖案直接切出畫面四邊，不要露出圖案的盡頭。', '找一個「破格」的元素——一顆不同色的杯子——放在三分點上。'],
    principles: ['symmetry'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-straight-verticals',
    title: '直的就要直',
    brief: '拍一個有明顯垂直線的東西：書櫃、門框、窗框、大樓。判斷標準：畫面左右兩側的垂直線都是直上直下，沒有往內縮或往外倒成梯形。',
    tips: ['手機和牆面平行、不要上下傾斜，垂直線就會直。', '退後一步用主鏡頭拍，比廣角鏡頭變形少。', '事後用編輯的「垂直透視」滑桿可以救一點，但先從拍好開始。'],
    principles: ['horizon-level'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-food-side-light',
    title: '側光拍便當',
    brief: '午餐時把便當或餐盤移到窗邊，讓光從側面來，拍一張食物照。判斷標準：食物表面看得到亮面和小小的影子，有立體感和油光，而不是頂燈照下來的平面。',
    tips: ['關掉頭頂的日光燈，混光會讓菜色變得灰灰的。', '影子那側太黑就拿菜單或白紙反光補一下。', '把便當盒的商標或塑膠袋移出畫面。'],
    principles: ['light-direction', 'exposure'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-complementary',
    title: '互補色配對',
    brief: '在家裡找一組互補色放在一起拍：橘色和藍色、黃色和紫色、紅色和綠色。判斷標準：畫面裡就這兩個顏色是主角，一個當主體一個當背景，其他色都很少。',
    tips: ['橘子放在藍色餐墊上、檸檬放在紫色布上，最快取材。', '兩色的面積別一樣大，一大一小才有主從。', '色彩對比強時，拍完可以稍微降飽和度，會更耐看。'],
    principles: ['color-harmony'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-mrt-lines',
    title: '捷運站的線',
    brief: '在捷運站找一組線：月台的黃線、手扶梯的扶手、天花板的燈條，讓線條從畫面一角延伸到主體。判斷標準：順著線看過去，視線會停在你想讓人看的地方。',
    tips: ['蹲低一點，線條在畫面裡會拉得更長。', '避開上下班尖峰時段，人少線條才乾淨。', '線的終點放一個人或一個出口，不要讓線通向空無一物。'],
    principles: ['leading-lines', 'perspective'],
    difficulty: 2,
    indoorOk: false,
  },
  {
    id: 'ch-panning',
    title: '追焦機車',
    brief: '站在路邊，手機跟著經過的機車一起橫向移動並在移動中按快門。判斷標準：機車和騎士相對清楚，背景拉成橫向的線條，看得出速度感。',
    tips: ['先用眼睛鎖定遠處來車，身體轉腰跟著移動，手不要單獨動。', '用連拍，按快門的當下手機仍然要繼續跟著移動。', '傍晚光線暗一點，快門自然變慢，背景更容易拖出線條。'],
    principles: ['shutter-motion', 'moment'],
    difficulty: 3,
    indoorOk: false,
  },
  {
    id: 'ch-glass-reflection',
    title: '櫥窗雙重影',
    brief: '站在一面櫥窗或玻璃門前，讓玻璃後面的東西和玻璃上的倒影同時出現，疊成一張。判斷標準：看得出兩層畫面，而且兩層彼此有關聯，例如街景倒映在櫥窗的模特兒身上。',
    tips: ['自己別入鏡：站到斜側面，或用衣服擋住身體的倒影。', '對焦點在玻璃後面的物件，倒影會自己浮上來。', '天色比室內亮時倒影最明顯，傍晚兩邊亮度接近會最平衡。'],
    principles: ['symmetry', 'depth-layers'],
    difficulty: 3,
    indoorOk: false,
  },
  {
    id: 'ch-doorway-frame',
    title: '門框外的世界',
    brief: '從室內或騎樓往外拍，讓門或拱門當成暗色的邊框，框裡是亮的街道或公園。判斷標準：框是暗的、框內是亮的，而且框內剛好有一個能看的主體。',
    tips: ['對焦點在框外的亮處，框自然會暗下來。', '框的四邊在畫面裡要都看得到，不要切掉一邊。', '等一台車或一個人經過框裡再按，比空景有故事。'],
    principles: ['framing', 'depth-layers'],
    difficulty: 2,
    indoorOk: false,
  },
  {
    id: 'ch-wall-person',
    title: '牆前一個人',
    brief: '找一面大而乾淨的牆（水泥牆、彩色鐵皮），請對方站在牆前靠一側，人只占畫面一小塊。判斷標準：牆的顏色和質感成為畫面的主要面積，人在三分線附近。',
    tips: ['人和牆之間留一步距離，影子才不會黏在牆上。', '請對方朝畫面留白的方向看，視線前面留空間。', '牆上的招牌、貼紙、電箱，能避就避。'],
    principles: ['negative-space', 'rule-of-thirds'],
    difficulty: 2,
    indoorOk: false,
  },
  {
    id: 'ch-step-closer',
    title: '靠近再靠近',
    brief: '選一個主體，先站在原地拍一張，往前走兩步再拍一張，再走兩步拍第三張。判斷標準：第三張裡沒有任何和主體無關的東西，看照片的人第一眼就知道你在拍什麼。',
    tips: ['用腳走過去，不要用手指放大，放大會糊。', '每靠近一步就檢查畫面邊緣有沒有多出來的雜物。', '太近對不到焦時退一點點，或改用微距模式。'],
    principles: ['simplify'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-save-highlights',
    title: '保住亮部',
    brief: '拍一個有亮處會過曝的場景：檯燈、窗、白色的杯子，先用手機自動拍一張，再把曝光滑桿往下拉一張。判斷標準：拉過的那張亮處看得到質感和細節，不再是一片死白。',
    tips: ['點對焦框後往下滑動，就是曝光補償。', '寧可整張暗一點，暗處後製拉得回來，白掉的救不了。', '拍完點開照片放大看最亮的地方，還有沒有紋理。'],
    principles: ['exposure'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-mixed-light',
    title: '混光咖啡店',
    brief: '進一間有黃色吊燈又有窗光的咖啡店，拍一張桌面。判斷標準：拍完看看杯子上有沒有一邊偏黃一邊偏藍，有的話想辦法改座位或後製把白盤子調回白色。',
    tips: ['坐到全窗光或全黃燈的位置，不要坐在兩種光交界。', '編輯時白平衡先讓白盤子變白，其他顏色會跟著對。', '救不回來時乾脆全張轉暖色，讓黃光變成氛圍。'],
    principles: ['white-balance'],
    difficulty: 2,
    indoorOk: true,
  },
  {
    id: 'ch-rainy-muted',
    title: '雨天低飽和',
    brief: '下雨的陰天出門，拍一張低飽和、灰藍色調的街景或公園，讓一件小小的鮮色東西當亮點，例如一支紅傘。判斷標準：整體是安靜的灰色，只有一個地方有顏色。',
    tips: ['陰天光線本來就柔，不要用濃豔濾鏡硬把它拉回晴天。', '後製降飽和度，再用「單色調整」把想留的紅色加回來。', '濕地面的反光是免費的前景，蹲低一點把它納進來。'],
    principles: ['saturation', 'golden-hour'],
    difficulty: 2,
    indoorOk: false,
  },
  {
    id: 'ch-market-hands',
    title: '夜市攤前的手',
    brief: '在夜市選一個攤位，拍老闆的手正在動作的瞬間：翻鐵板、灑粉、夾東西。判斷標準：手的動作看得出來在做什麼，手不糊，攤位的燈光把手照得夠亮。',
    tips: ['先跟老闆點頭示意，站在側邊不要擋客人。', '對焦點鎖在鐵板或工作檯，等手進來就連拍。', '攤位的燈就是主光，不要開閃光燈。'],
    principles: ['moment', 'noise'],
    difficulty: 3,
    indoorOk: false,
  },
  {
    id: 'ch-long-exposure-river',
    title: '河濱長曝',
    brief: '傍晚到河濱，把手機固定在欄杆或小腳架上，用長曝光模式拍水面和天空。判斷標準：水面變得像鏡子或絲綢一樣平滑，天空的雲有流動感，橋和岸邊仍然清楚。',
    tips: ['一定要固定手機，手持長曝光整張都會糊。', '長曝光時間從三秒起試，越長水面越平。', '對岸的水平線要拉平，長曝光照片一歪就很明顯。'],
    principles: ['shutter-motion', 'horizon-level'],
    difficulty: 3,
    indoorOk: false,
  },
  {
    id: 'ch-blind-shadows',
    title: '百葉窗光影',
    brief: '上午或下午陽光斜射時，拍一張百葉窗或窗格投在牆上、地上、人身上的條紋影子。判斷標準：亮條和暗條都看得到細節，而且條紋的方向在畫面裡是有秩序的。',
    tips: ['沒有百葉窗就用手指、叉子、書架的縫隙做出條紋。', '對焦點在亮條上，暗條才不會死黑，亮條也不會白掉。', '讓條紋斜著穿過畫面，比水平橫過更有動感。'],
    principles: ['light-direction', 'symmetry'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-kid-eye-level',
    title: '與小孩同高',
    brief: '幫小孩或寵物拍照時，蹲下或坐到地板上，讓鏡頭和對方的眼睛一樣高，等他看向你或專心玩的時候拍。判斷標準：照片裡看不到他的頭頂，而是看到他的正臉，背景是牆或遠處而不是地板。',
    tips: ['身體先蹲好再叫他，不要邊蹲邊拍。', '他專心玩的時候比叫他看鏡頭更自然，多等三秒。', '房間亮度不夠就靠近窗邊，動來動去的小孩需要光。'],
    principles: ['perspective', 'moment'],
    difficulty: 2,
    indoorOk: true,
  },
  {
    id: 'ch-park-layers',
    title: '公園三層景',
    brief: '在公園找出前景、中景、遠景三層，例如前面的欄杆或花、中間的長椅或人、遠處的樹或大樓。判斷標準：閉一隻眼看照片，仍能感覺到三個距離，而不是一張貼在牆上的圖。',
    tips: ['先決定中景主體，再前後走動找前景。', '前景放在畫面下方或一側，不要蓋住中景。', '主體放在三分線上，三層才不會擠成一條直線。'],
    principles: ['depth-layers', 'rule-of-thirds'],
    difficulty: 2,
    indoorOk: false,
  },
  {
    id: 'ch-steady-grip',
    title: '手肘夾緊',
    brief: '晚上在燈光不太亮的房間，拍一張桌上的小物：先隨手一按，再用「雙手持機、手肘夾緊身體、按快門時吐氣」的方式拍一張。判斷標準：放大看邊緣，第二張的文字或紋理明顯比第一張清楚。',
    tips: ['用音量鍵當快門，比手指戳螢幕穩得多。', '先擦一下鏡頭，霧掉的鏡頭再穩也拍不清楚。', '可以把手機靠在杯子或書上，比手更穩。'],
    principles: ['sharpness'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-flat-day-contrast',
    title: '陰天拉對比',
    brief: '陰天出門拍一張看起來灰灰的街景，再回家後製：拉高對比、加一點黑色、降一點亮部。判斷標準：修過的那張暗處是真的暗、亮處還在，畫面不再霧霧的，顏色也不能變得刺眼。',
    tips: ['先動「對比」和「黑色」，不要先動飽和度。', '拉對比後顏色會跟著變濃，飽和度要記得往回收一點。', '天空灰白時可以把亮部降一點，雲的層次會浮出來。'],
    principles: ['dynamic-range', 'saturation'],
    difficulty: 2,
    indoorOk: false,
  },
  {
    id: 'ch-fan-freeze',
    title: '電扇葉片停住',
    brief: '在窗邊或亮燈下開電風扇，拍一張轉動中的葉片。判斷標準：葉片是一片一片清楚的形狀，而不是一團灰色的圓盤。拍不到就換更亮的位置，或降一檔風速再試。',
    tips: ['光越亮快門越快，白天把電扇搬到窗邊最有效。', '連拍多按幾張，總會有一張葉片剛好清楚。', '有「專業模式」的手機把快門設到 1/1000 秒以上。'],
    principles: ['shutter-motion'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-fridge-blue',
    title: '便利商店冰箱前',
    brief: '走進便利商店，站在飲料冰箱前拍一張：冰箱的白冷光、整排的瓶罐顏色、玻璃門的反光。判斷標準：白色的瓶身沒有偏藍或偏綠，架上整排的顏色有規律，不是雜亂的。',
    tips: ['正對冰箱拍，一排排的瓶子會變成整齊的色塊。', '冰箱燈通常偏冷，白平衡往暖調一點瓶身才會白。', '選一排同色系的飲料當主角，別把整面冰箱都塞進來。'],
    principles: ['white-balance', 'color-harmony'],
    difficulty: 2,
    indoorOk: true,
  },
  {
    id: 'ch-stairwell-down',
    title: '樓梯間往下看',
    brief: '站在樓梯最上層，把手機伸出欄杆往下拍旋轉或折返的樓梯。判斷標準：樓梯的線條在畫面裡繞了一圈或折了幾次，看的人會有點頭暈，這就是對的。',
    tips: ['手機拿穩、手腕套好，伸出欄杆時要小心。', '正上方垂直往下看和斜著看是兩張完全不同的照片，兩種都試。', '有人正好在走樓梯時按下去，比空樓梯多一個焦點。'],
    principles: ['perspective', 'leading-lines'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-curtain-light',
    title: '窗簾透光',
    brief: '白天拉上薄窗簾，拍窗簾被陽光透亮的樣子，最好前面有一株植物或一個人的側影。判斷標準：窗簾的布紋看得到，沒有整片白掉；前面的東西是柔和的暗色而不是全黑。',
    tips: ['對焦點點在窗簾上，再把曝光滑桿往下拉一點。', '窗簾有摺痕就把它拉整齊，或故意留大摺讓光影更明顯。', 'HDR 開著，室內和窗簾的亮度差才顧得住。'],
    principles: ['exposure', 'dynamic-range'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-jump-freeze',
    title: '跳起來',
    brief: '在公園或空曠處，請對方跳起來，拍下他離地最高的那一瞬間。判斷標準：腳離地、身體在最高點、頭髮或衣服是飄起來的，而且人是清楚的。',
    tips: ['數「一、二、三」在三的時候他跳、你連拍，之後從中選。', '蹲低一點拍，人會看起來跳得更高。', '找白天亮的地方拍，光不夠人就會糊。'],
    principles: ['shutter-motion', 'moment'],
    difficulty: 3,
    indoorOk: false,
  },
  {
    id: 'ch-overpass-view',
    title: '天橋俯瞰',
    brief: '走上天橋或大樓的高樓層，往下拍街道、車流或人群。判斷標準：畫面裡看得出「從上面往下看」，路面上的線條把畫面切成幾塊，人變成小小的點。',
    tips: ['讓一條馬路或斑馬線斜著穿過畫面，比正對著拍有張力。', '等紅燈時車停成一排、綠燈時人群過馬路，各拍一張比較。', '不要用放大，用主鏡頭拍再裁切更清楚。'],
    principles: ['perspective', 'leading-lines'],
    difficulty: 2,
    indoorOk: false,
  },
  {
    id: 'ch-centered-symmetry',
    title: '正中對稱建築',
    brief: '找一個左右對稱的建築或空間——廟門、大樓入口、地下道——站在中軸線上，把它放正中央拍。判斷標準：把照片左右對折，兩邊幾乎重疊，垂直線筆直不歪。',
    tips: ['腳先找到地面的中線（磁磚縫、地磚接縫），再把手機舉起。', '格線打開，讓中間那條垂直線對準建築中軸。', '這是少數「放正中央才對」的題，不要下意識又往三分點挪。'],
    principles: ['symmetry', 'horizon-level'],
    difficulty: 2,
    indoorOk: false,
  },
  {
    id: 'ch-zebra-moment',
    title: '斑馬線上的人',
    brief: '在路口斑馬線旁等綠燈，拍一個過馬路的人剛好踩在斑馬線白條上、和其他人拉開距離的那一刻。判斷標準：白條變成畫面的線條，人的步伐是清楚的、單獨的，不是一團人潮。',
    tips: ['綠燈剛亮和快結束時人最少，先觀察兩個燈號再拍。', '蹲低讓斑馬線在畫面裡拉長，人的腿部動作更明顯。', '對焦鎖定在斑馬線中段，人走到那一格就按。'],
    principles: ['moment', 'leading-lines'],
    difficulty: 3,
    indoorOk: false,
  },
  {
    id: 'ch-three-fruits',
    title: '三顆水果',
    brief: '拿三顆同色系的水果——三顆橘子、三顆蘋果——放在乾淨的桌面或布上拍一張。判斷標準：水果顏色和背景是相近色或明顯對比，畫面剩下的空間比水果多。',
    tips: ['三顆不要排成一直線，兩顆靠近一顆稍遠會比較自然。', '背景選單色布或白桌，花紋會搶戲。', '窗邊側光讓水果有亮面，看起來才新鮮。'],
    principles: ['color-harmony', 'negative-space'],
    difficulty: 1,
    indoorOk: true,
  },
  {
    id: 'ch-dew-macro',
    title: '葉尖的水珠',
    brief: '在盆栽葉子上噴一點水，或雨後找戶外的葉子，用微距或靠很近拍一顆水珠。判斷標準：水珠的邊緣清楚，裡面甚至有倒影或光點，葉子的紋路在水珠周圍還看得到。',
    tips: ['對焦點點在水珠上，手機會自動切到微距模式。', '手拿不穩就把手肘靠在桌上，或等沒有風再拍。', '讓光從側後方來，水珠才會亮起來。'],
    principles: ['sharpness', 'depth-of-field'],
    difficulty: 2,
    indoorOk: true,
  },
  {
    id: 'ch-lantern-exposure',
    title: '燈籠不過曝',
    brief: '晚上到廟口或夜市，拍一排亮著的燈籠或招牌，讓燈籠上的字和紋路看得清楚。判斷標準：燈籠是紅色或黃色而不是白色，字看得出來，周圍的暗處還保有一點細節不是全黑。',
    tips: ['點一下最亮的燈籠對焦，再把曝光滑桿往下拉到字浮出來。', '暗處顆粒多就開夜景模式，同時手肘夾緊撐住。', '選一排燈籠斜著延伸出去，比正面一顆更有層次。'],
    principles: ['exposure', 'noise'],
    difficulty: 3,
    indoorOk: false,
  },
  {
    id: 'ch-long-shadow',
    title: '影子拉很長',
    brief: '日落前半小時到空曠處（河濱、操場、停車場），背對太陽拍自己或朋友被拉得很長的影子。判斷標準：影子長度至少是人身高的兩倍，影子在畫面裡是完整的一條。',
    tips: ['蹲低一點拍，影子在畫面裡會顯得更長。', '手舉高、腳張開，影子的形狀會比站直更有趣。', '注意自己的影子別壓到主體的影子，站到旁邊拍。'],
    principles: ['golden-hour', 'perspective'],
    difficulty: 2,
    indoorOk: false,
  },
]
