// Wikimedia Commons 真實好壞對比題（自動抓取＋人審撰文）。
// 每組 good 取自 Featured pictures，weak 為同主題的一般上傳；兩張皆為 CC0 / PD / CC BY / CC BY-SA。
// 圖 id 使用 img-<category>-5NN 區段，避免與 pool/ 的 001 起跳序號衝突。
// src 為 API 的 960px thumburl（API 若回 thumb.wikimedia.org 主機則改回 upload.wikimedia.org 同路徑）；
// 原圖小於 960px 時 API 直接回原圖網址（已去掉 utm 追蹤參數）。寬度數字一律不手改。
import type { ComparisonPair } from './types'

export const PAIRS: ComparisonPair[] = [
  {
    id: 'pair-001',
    theme: '海邊日落',
    good: {
      id: 'img-landscape-501',
      title: '風箏衝浪者與海灘日落',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Kitesurfer_at_sunset%2C_Workum%2C_may_2017.jpg/960px-Kitesurfer_at_sunset%2C_Workum%2C_may_2017.jpg',
      width: 5500,
      height: 2319,
      author: 'Villy Fink Isaksen',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Kitesurfer_at_sunset,_Workum,_may_2017.jpg',
    },
    weak: {
      id: 'img-landscape-502',
      title: '午後海灘與逆光海面',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/P%C5%ABp%C5%ABkea_Sunset_Beach_2_Oahu_Hawaii_Photo_Don_Ramey_Logan.jpg/960px-P%C5%ABp%C5%ABkea_Sunset_Beach_2_Oahu_Hawaii_Photo_Don_Ramey_Logan.jpg',
      width: 2592,
      height: 1944,
      author: 'Don Ramey Logan',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:P%C5%ABp%C5%ABkea_Sunset_Beach_2_Oahu_Hawaii_Photo_Don_Ramey_Logan.jpg',
    },
    principles: ['golden-hour', 'exposure', 'simplify'],
    explanation:
      '好圖等到太陽貼近海平面才按下快門，整片天空染成橘紅，散步的人與風箏都變成乾淨的剪影，海平面放在下三分線，畫面只留天、海、人三層。另一張拍在太陽還很高的午後，逆光讓海面反光刺眼、天空接近死白，前景一大片凌亂的沙地占了一半以上，人群變成分散的小點，主體就不明確。建議晚一個小時再來，並蹲低或前進幾步，把腳印沙地裁掉。',
  },
  {
    id: 'pair-002',
    theme: '城市夜景',
    good: {
      id: 'img-landscape-503',
      title: '魁北克古城藍調時刻',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Qu%C3%A9bec_city_at_night%2C_view_from_L%C3%A9vis_city.jpg/960px-Qu%C3%A9bec_city_at_night%2C_view_from_L%C3%A9vis_city.jpg',
      width: 5882,
      height: 3860,
      author: 'Wilfredor',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Qu%C3%A9bec_city_at_night,_view_from_L%C3%A9vis_city.jpg',
    },
    weak: {
      id: 'img-landscape-504',
      title: '高樓俯瞰紐約夜色',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/New_York_City_by_Night_Skyline_-_Flickr_-_Timo_Kohlenberg.jpg/960px-New_York_City_by_Night_Skyline_-_Flickr_-_Timo_Kohlenberg.jpg',
      width: 1024,
      height: 683,
      author: 'Timo Kohlenberg',
      license: 'CC BY-SA 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:New_York_City_by_Night_Skyline_-_Flickr_-_Timo_Kohlenberg.jpg',
    },
    principles: ['noise', 'saturation', 'golden-hour'],
    explanation:
      '好圖選在日落後的藍調時刻，天空還有粉紫殘光，古堡的暖黃燈光與冷色天空形成對比，長曝光讓水面平滑、暗部乾淨。另一張從高處拍全黑的夜空，感光度拉高之後雲層與暗部都帶著粗顆粒，街燈紅橘色也被推得過飽和，細節糊成一團。夜景其實不是越黑越好，天還微亮時拍，手機不必硬撐高 ISO，畫面反而更乾淨。',
  },
  {
    id: 'pair-003',
    theme: '森林步道',
    good: {
      id: 'img-landscape-505',
      title: '晨霧斜射光下的林間小徑',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Slezsk%C3%A9_Beskydy_-_Ryt%C3%AD%C5%99sk%C3%A1_stezka_%28cesta_N%C3%BDdek_-_Velk%C3%A1_%C4%8Cantoryje%29.JPG/960px-Slezsk%C3%A9_Beskydy_-_Ryt%C3%AD%C5%99sk%C3%A1_stezka_%28cesta_N%C3%BDdek_-_Velk%C3%A1_%C4%8Cantoryje%29.JPG',
      width: 3000,
      height: 2000,
      author: 'Pudelek (Marcin Szala)',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Slezsk%C3%A9_Beskydy_-_Ryt%C3%AD%C5%99sk%C3%A1_stezka_(cesta_N%C3%BDdek_-_Velk%C3%A1_%C4%8Cantoryje).JPG',
    },
    weak: {
      id: 'img-landscape-506',
      title: '正午陽光下的泥濕林道',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Muddy_forest_path%2C_Ketelbossen%2C_Waasmunster%2C_2025.jpg/960px-Muddy_forest_path%2C_Ketelbossen%2C_Waasmunster%2C_2025.jpg',
      width: 4000,
      height: 6016,
      author: 'DimiTalen',
      license: 'CC0',
      licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Muddy_forest_path,_Ketelbossen,_Waasmunster,_2025.jpg',
    },
    principles: ['golden-hour', 'light-direction', 'exposure'],
    explanation:
      '好圖遇到晨霧與低角度斜射光，光束在樹幹間畫出一道道柔和的線，落葉小徑從左下彎向遠處，明暗過渡細膩。另一張是接近正午的頂光，樹影在地面切出生硬的條紋，樹梢後方的天空過曝成白色，泥濕的路面與水窪又占了前景大半，眼睛不知道該停在哪裡。同一條路，等清晨或陰天光線變柔和再來，效果會完全不同。',
  },
  {
    id: 'pair-004',
    theme: '教堂內部',
    good: {
      id: 'img-architecture-501',
      title: '明斯特主教座堂祭壇中軸線',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/M%C3%BCnster%2C_St.-Paulus-Dom%2C_Alter_Chor_--_2019_--_3789-93.jpg/960px-M%C3%BCnster%2C_St.-Paulus-Dom%2C_Alter_Chor_--_2019_--_3789-93.jpg',
      width: 3003,
      height: 4805,
      author: 'Dietmar Rabich',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:M%C3%BCnster,_St.-Paulus-Dom,_Alter_Chor_--_2019_--_3789-93.jpg',
    },
    weak: {
      id: 'img-architecture-502',
      title: '白牆小教堂中殿',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Interior_Nave_Thomas_Church_Mount_Chennai_Aug22_A7C_02257.jpg/960px-Interior_Nave_Thomas_Church_Mount_Chennai_Aug22_A7C_02257.jpg',
      width: 5620,
      height: 3747,
      author: 'Timothy A. Gonsalves',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Interior_Nave_Thomas_Church_Mount_Chennai_Aug22_A7C_02257.jpg',
    },
    principles: ['symmetry', 'simplify'],
    explanation:
      '好圖站在中殿正中央、相機保持水平，拱頂的肋線、兩側的柱列、長椅與祭壇全部對稱收攏，玫瑰窗成為視線終點，畫面沒有多餘的東西。另一張同樣想拍中軸對稱，但相機略偏右，左右拱門與掛畫不對等，天花板的吊扇、角落的音箱與前排信眾都分散了注意力。拍對稱建築時多花十秒對齊中線，並等前景淨空，秩序感就出來了。',
  },
  {
    id: 'pair-005',
    theme: '大橋結構',
    good: {
      id: 'img-architecture-503',
      title: '瓦斯科達伽馬大橋黑白長曝',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Vasco_da_Gama_Bridge_B%26W_%28crop2%29.jpg/960px-Vasco_da_Gama_Bridge_B%26W_%28crop2%29.jpg',
      width: 5159,
      height: 2899,
      author: 'William Warby（裁切：Bruce1ee）',
      license: 'CC BY 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Vasco_da_Gama_Bridge_B%26W_(crop2).jpg',
    },
    weak: {
      id: 'img-architecture-504',
      title: '空拍市區鐵道橋',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Guindy_Railway_Bridge_Adyar_River_Chennai_Jul18_DSC05379.jpg/960px-Guindy_Railway_Bridge_Adyar_River_Chennai_Jul18_DSC05379.jpg',
      width: 5278,
      height: 3299,
      author: 'Timothy A. Gonsalves',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Guindy_Railway_Bridge_Adyar_River_Chennai_Jul18_DSC05379.jpg',
    },
    principles: ['negative-space', 'simplify', 'shutter-motion'],
    explanation:
      '好圖用長時間曝光把天空與水面抹成平滑的灰色，只留下橋塔、拉索與一路延伸到遠方的橋身，大面積留白讓弧線的節奏格外清楚，黑白處理又拿掉了色彩的干擾。另一張從高處俯拍，橋與火車確實有趣，但四周擠滿了密密麻麻的房子、河流與空地，橋只是畫面中的一條斜線，觀者要花時間才能找到主體。想突顯結構之美，先想辦法讓背景安靜下來。',
  },
  {
    id: 'pair-006',
    theme: '貓咪特寫',
    good: {
      id: 'img-people-animals-501',
      title: '虎斑貓的視線平視特寫',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Cat_November_2010-1a.jpg/960px-Cat_November_2010-1a.jpg',
      width: 1795,
      height: 2397,
      author: 'Alvesgaspar',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cat_November_2010-1a.jpg',
    },
    weak: {
      id: 'img-people-animals-502',
      title: '室內燈光下的暹羅貓',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Photo_of_my_cat_Calinoux.jpg/960px-Photo_of_my_cat_Calinoux.jpg',
      width: 3120,
      height: 4160,
      author: 'Calinoux',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Photo_of_my_cat_Calinoux.jpg',
    },
    principles: ['white-balance', 'perspective', 'noise'],
    explanation:
      '好圖蹲到與貓眼同高，背景是失焦的枯枝與天空，色調乾淨，綠眼睛正對鏡頭成為焦點。另一張在室內黃燈下由上往下拍，整張偏橘黃，白色的爪子與地磚都變成米色，高感光度也帶出雜訊；從站姿俯拍會讓貓看起來短小、與地面貼在一起。改善方法很直接：把手機放到地面高度，開窗借自然光或把白平衡調到白色真的是白色。',
  },
  {
    id: 'pair-007',
    theme: '野鳥特寫',
    good: {
      id: 'img-people-animals-503',
      title: '燕尾蜂虎停枝側面',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Swallow-tailed_bee-eater_%28Merops_hirundineus_chrysolaimus%29.jpg/960px-Swallow-tailed_bee-eater_%28Merops_hirundineus_chrysolaimus%29.jpg',
      width: 1853,
      height: 1853,
      author: 'Charles J. Sharp',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Swallow-tailed_bee-eater_(Merops_hirundineus_chrysolaimus).jpg',
    },
    weak: {
      id: 'img-people-animals-504',
      title: '樹梢背光下的小鳥',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Little_bird_on_branch%2C_New_Orleans.jpg/960px-Little_bird_on_branch%2C_New_Orleans.jpg',
      width: 4608,
      height: 3072,
      author: 'Terri Stewart',
      license: 'CC BY-SA 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Little_bird_on_branch,_New_Orleans.jpg',
    },
    principles: ['exposure', 'light-direction', 'moment'],
    explanation:
      '好圖光線從側前方打在鳥身上，綠、黃、藍的羽色層次分明，背景是均勻的棕綠色，鳥頭側轉、眼睛有神，正是最能看清特徵的一刻。另一張鳥背對鏡頭、整隻逆光成剪影，天空過曝成一片白，枝葉又纏在前面，看不出羽色也看不到眼睛。拍鳥時先看太陽在哪裡，繞到讓光照在鳥身上的那一側，再等它轉頭或抬頭的瞬間。',
  },
  {
    id: 'pair-008',
    theme: '花朵特寫',
    good: {
      id: 'img-still-life-501',
      title: '藍色雪光花與深色背景',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Blue_Star_Flower_Focus_Stack-20220410-RM-170959.jpg/960px-Blue_Star_Flower_Focus_Stack-20220410-RM-170959.jpg',
      width: 5182,
      height: 3712,
      author: 'Ermell',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Blue_Star_Flower_Focus_Stack-20220410-RM-170959.jpg',
    },
    weak: {
      id: 'img-still-life-502',
      title: '花叢中的白菊',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flower_Macro_Photo_01.jpg/960px-Flower_Macro_Photo_01.jpg',
      width: 2304,
      height: 4096,
      author: 'Antriksh daya',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Flower_Macro_Photo_01.jpg',
    },
    principles: ['depth-of-field', 'subject-placement', 'simplify'],
    explanation:
      '好圖只讓一朵花進入畫面，花莖從左下斜切進來、花心落在偏右的位置，背景拉成柔和的深綠，所有細節都在花瓣上。另一張把花放在直幅的正中央，四周是被人像模式強行虛化的枝葉，邊緣有明顯的塗抹痕跡，左上的枯枝與下方的黃色小花也在搶注意。與其靠軟體虛化，不如靠近一點、讓花離背景遠一點，順手把花移出正中央。',
  },
  {
    id: 'pair-009',
    theme: '咖啡與麵包',
    good: {
      id: 'img-still-life-503',
      title: '油燈側光下的咖啡與麵包',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Pinoy_Pandesal.jpg/960px-Pinoy_Pandesal.jpg',
      width: 5472,
      height: 3648,
      author: 'Jessartcam',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Pinoy_Pandesal.jpg',
    },
    weak: {
      id: 'img-still-life-504',
      title: '樹樁上的一杯濃縮咖啡',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Huai_Nam_Dang_National_Park%2C_Espresso_coffee_cup%2C_Tree_stump%2C_Thailand.jpg/960px-Huai_Nam_Dang_National_Park%2C_Espresso_coffee_cup%2C_Tree_stump%2C_Thailand.jpg',
      width: 4032,
      height: 2688,
      author: 'Vyacheslav Argenberg',
      license: 'CC BY 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Huai_Nam_Dang_National_Park,_Espresso_coffee_cup,_Tree_stump,_Thailand.jpg',
    },
    principles: ['light-direction', 'depth-layers', 'color-harmony'],
    explanation:
      '好圖用一盞油燈當側後方的光源，麵包表皮出現亮面與陰影、蒸氣被光勾出輪廓，前景的黃布、中景的麵包、後景的咖啡杯與罐子排成三層，暖黃搭配一點藍布做對比。另一張由正上方俯拍，光線平均、沒有陰影，杯子與年輪都只有一層，色調全是棕色，畫面安穩但少了立體感與故事感。拍食物時把光源移到側邊，再放一個前景，質感立刻不一樣。',
  },
  {
    id: 'pair-010',
    theme: '街道巷弄',
    good: {
      id: 'img-architecture-505',
      title: '首爾桂洞街黃金時刻',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Gyedong-gil_street_with_climbing_plants_at_golden_hour_in_Seoul_South_Korea.jpg/960px-Gyedong-gil_street_with_climbing_plants_at_golden_hour_in_Seoul_South_Korea.jpg',
      width: 6631,
      height: 3949,
      author: 'Basile Morin',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Gyedong-gil_street_with_climbing_plants_at_golden_hour_in_Seoul_South_Korea.jpg',
    },
    weak: {
      id: 'img-architecture-506',
      title: '小鎮街角的白色建築',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Brook_House%2C_Old_Town_Street%2C_Dawlish_-_geograph.org.uk_-_7036998.jpg/960px-Brook_House%2C_Old_Town_Street%2C_Dawlish_-_geograph.org.uk_-_7036998.jpg',
      width: 1024,
      height: 768,
      author: 'Stephen Craven',
      license: 'CC BY-SA 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Brook_House,_Old_Town_Street,_Dawlish_-_geograph.org.uk_-_7036998.jpg',
    },
    principles: ['leading-lines', 'depth-layers', 'golden-hour'],
    explanation:
      '好圖站在路中央，讓地磚、黃線與兩側店面一路收向遠方，左邊咖啡店的木窗是前景、中段的綠牆是中景、遠處的房子是背景，傍晚側光把牆面與招牌都染得溫暖。另一張在正午順光下正面拍建築，牆面白得發亮、幾乎沒有陰影，右前方的水泥柱與人孔蓋卡在最前面，畫面沒有引導方向，只是紀錄了一棟房子。往路口移幾步、等光斜一點，街道就會替你帶路。',
  },
  {
    id: 'pair-011',
    theme: '雪地樹林',
    good: {
      id: 'img-landscape-507',
      title: '希普卡山口霧凇雪林',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Snow_Scene_at_Shipka_Pass_1.JPG/960px-Snow_Scene_at_Shipka_Pass_1.JPG',
      width: 2576,
      height: 1932,
      author: 'Psy guy',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Snow_Scene_at_Shipka_Pass_1.JPG',
    },
    weak: {
      id: 'img-landscape-508',
      title: '雪地枝椏與陰天遠景',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Snow_in_the_Landscape_-_geograph.org.uk_-_1655896.jpg/960px-Snow_in_the_Landscape_-_geograph.org.uk_-_1655896.jpg',
      width: 3872,
      height: 2592,
      author: 'Peter Trimming',
      license: 'CC BY-SA 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Snow_in_the_Landscape_-_geograph.org.uk_-_1655896.jpg',
    },
    principles: ['dynamic-range', 'simplify', 'exposure'],
    explanation:
      '好圖在陰天的柔光下拍霧凇，整張畫面幾乎只有白與淺灰兩種色調，樹形一棵棵分得清楚，雪的層次沒有被曬掉。另一張把大量深色枝椏放在前景，遠方卻是接近過曝的天空與雪地，相機在明暗之間兩邊都顧不好，枝條又擠在畫面各處，讓人看不出主體是樹還是遠景。大反差的雪景可以開 HDR 或對著雪地略減曝光，也可以乾脆只拍近處的一叢枝條。',
  },
  {
    id: 'pair-012',
    theme: '沙漠沙丘',
    good: {
      id: 'img-landscape-509',
      title: '索蘇斯黎的紅色沙丘稜線',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Sossusvlei_Dune_Namib_Desert_Namibia_Luca_Galuzzi_2004.JPG/960px-Sossusvlei_Dune_Namib_Desert_Namibia_Luca_Galuzzi_2004.JPG',
      width: 2000,
      height: 1333,
      author: 'Luca Galuzzi (Lucag)',
      license: 'CC BY-SA 2.5',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sossusvlei_Dune_Namib_Desert_Namibia_Luca_Galuzzi_2004.JPG',
    },
    weak: {
      id: 'img-landscape-510',
      title: '風紋沙地與斜向沙脊',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Sand_dunes_in_the_desert%2C_Sahara_Desert%2C_Dakhla_Oasis%2C_Egypt.jpg/960px-Sand_dunes_in_the_desert%2C_Sahara_Desert%2C_Dakhla_Oasis%2C_Egypt.jpg',
      width: 3072,
      height: 2048,
      author: 'Vyacheslav Argenberg',
      license: 'CC BY 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sand_dunes_in_the_desert,_Sahara_Desert,_Dakhla_Oasis,_Egypt.jpg',
    },
    principles: ['light-direction', 'subject-placement', 'leading-lines'],
    explanation:
      '好圖利用低角度側光，沙丘一面亮橘一面深褐，稜線成為一條彎進畫面的 S 形引導線，頂端一個小小的人影告訴你這座沙丘有多巨大。另一張的光線較平，沙面只剩細碎的風紋質感，唯一的線條是上方一道橫向沙脊，畫面裡沒有可以停留的主體，看不出深度也看不出比例。拍沙漠請等清晨或傍晚讓陰影長出來，並找一條稜線把視線帶進去。',
  },
  {
    id: 'pair-013',
    theme: '瀑布水流',
    good: {
      id: 'img-landscape-511',
      title: '塔斯馬尼亞 Snug Falls 長曝',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Snug_Falls_2.jpg/960px-Snug_Falls_2.jpg',
      width: 1944,
      height: 1296,
      author: 'JJ Harrison',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Snug_Falls_2.jpg',
    },
    weak: {
      id: 'img-landscape-512',
      title: '雨季瀑布近距離仰拍',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/June_2025_photo_of_Bandarkum_Waterfall%2C_also_called_the_main_Napittachora_Waterfall%2C_by_Owais_Al_Qarni_01.jpg/960px-June_2025_photo_of_Bandarkum_Waterfall%2C_also_called_the_main_Napittachora_Waterfall%2C_by_Owais_Al_Qarni_01.jpg',
      width: 3060,
      height: 4080,
      author: 'Owais Al Qarni',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:June_2025_photo_of_Bandarkum_Waterfall,_also_called_the_main_Napittachora_Waterfall,_by_Owais_Al_Qarni_01.jpg',
    },
    principles: ['shutter-motion', 'exposure', 'depth-layers'],
    explanation:
      '好圖用慢速快門把水流拉成絲綢般的白線，前景的苔石、中景的溪流、後景的岩壁與樹林層層堆疊，白色水流被控制在不過曝的範圍。另一張站在水中近距離用手機快拍，水珠被高速快門凝結成一顆顆白點，整片水花亮到失去細節，畫面下半部全是同一種質感，沒有前後層次。想要絲綢感可以用手機的長曝光或夜景模式並固定手機，同時對著亮部減一點曝光。',
  },
  {
    id: 'pair-014',
    theme: '海邊燈塔',
    good: {
      id: 'img-architecture-507',
      title: '挪威海上紅色燈塔的夕照',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/2016-11-13_01_Kjeungskj%C3%A6r_Lighthouse%2C_S%C3%B8r-Tr%C3%B8ndelag%2C_Norway.jpg/960px-2016-11-13_01_Kjeungskj%C3%A6r_Lighthouse%2C_S%C3%B8r-Tr%C3%B8ndelag%2C_Norway.jpg',
      width: 6000,
      height: 3257,
      author: 'Gordon Leggett',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:2016-11-13_01_Kjeungskj%C3%A6r_Lighthouse,_S%C3%B8r-Tr%C3%B8ndelag,_Norway.jpg',
    },
    weak: {
      id: 'img-architecture-508',
      title: '海邊白色燈塔正面照',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Hoge_vuurtoren_van_Heist_25-06-2019_17-34-14.jpg/960px-Hoge_vuurtoren_van_Heist_25-06-2019_17-34-14.jpg',
      width: 2956,
      height: 5269,
      author: 'Paul Hermans',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Hoge_vuurtoren_van_Heist_25-06-2019_17-34-14.jpg',
    },
    principles: ['rule-of-thirds', 'color-harmony', 'golden-hour'],
    explanation:
      '好圖把紅色燈塔放在右三分線上，左側留出海面與遠方島影，傍晚斜光把紅牆照得飽滿，紅橙與海天的藍是一組互補色。另一張把白色燈塔擺在直幅的正中央、上下頂到邊，午後霧霾讓天空灰白、塔身平淡，背後又有一架風車與塔身重疊。拍高塔時試著把它移到畫面的一側，留一點呼吸空間，並挑光有顏色的時段。',
  },
  {
    id: 'pair-015',
    theme: '港口帆船',
    good: {
      id: 'img-landscape-513',
      title: '芝加哥碼頭日落帆船',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Muelle_Monroe%2C_Chicago%2C_Illinois%2C_Estados_Unidos%2C_2012-10-20%2C_DD_10.jpg/960px-Muelle_Monroe%2C_Chicago%2C_Illinois%2C_Estados_Unidos%2C_2012-10-20%2C_DD_10.jpg',
      width: 5436,
      height: 1945,
      author: 'Diego Delso',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Muelle_Monroe,_Chicago,_Illinois,_Estados_Unidos,_2012-10-20,_DD_10.jpg',
    },
    weak: {
      id: 'img-landscape-514',
      title: '夏日午後的碼頭遊艇',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Houseboat_and_boats_at_Monroe_Harbor%2C_Chicago%2C_Illinois%2C_US_in_July_2022.jpg/960px-Houseboat_and_boats_at_Monroe_Harbor%2C_Chicago%2C_Illinois%2C_US_in_July_2022.jpg',
      width: 6230,
      height: 4156,
      author: 'Jules Verne Times Two',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Houseboat_and_boats_at_Monroe_Harbor,_Chicago,_Illinois,_US_in_July_2022.jpg',
    },
    principles: ['simplify', 'golden-hour', 'color-harmony'],
    explanation:
      '好圖在日落時分用橫幅收進整片停泊的帆船，天空的粉橘與海面的淡藍相互呼應，桅杆稀疏地散布，畫面安靜有節奏。另一張在正午拍碼頭，數十根桅杆與纜繩交錯在一起，遊艇、遮陽篷、盆栽全都亮度相近，眼睛找不到落點。碼頭這種本來就很雜的場景，可以退遠一點讓船變小、或只挑一艘船當主角，並等傍晚光線幫你統一色調。',
  },
  {
    id: 'pair-016',
    theme: '田野孤樹',
    good: {
      id: 'img-landscape-515',
      title: '孤樹與收割後的麥田',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Campilhas_July_2015-1.jpg/960px-Campilhas_July_2015-1.jpg',
      width: 11262,
      height: 3279,
      author: 'Alvesgaspar',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Campilhas_July_2015-1.jpg',
    },
    weak: {
      id: 'img-landscape-516',
      title: '初夏麥田與樹林',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Wheat_field_-_geograph.org.uk_-_7256475.jpg/960px-Wheat_field_-_geograph.org.uk_-_7256475.jpg',
      width: 1024,
      height: 684,
      author: 'N Chadwick',
      license: 'CC BY-SA 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Wheat_field_-_geograph.org.uk_-_7256475.jpg',
    },
    principles: ['negative-space', 'subject-placement', 'rule-of-thirds'],
    explanation:
      '好圖用超寬的橫幅，把唯一的一棵樹放在左邊三分線附近，其餘留給起伏的麥田與淡藍天空，大量留白反而讓那棵樹格外突出。另一張畫面裡是均勻的麥田、一排樹林和雲，每一區的份量差不多，沒有哪個元素可以當主角，地平線也落在畫面中間偏上，讀起來就是一張紀錄照。拍田野時先找一個焦點——一棵樹、一條小路、一間農舍——再決定把它放在哪個交點上。',
  },
  {
    id: 'pair-017',
    theme: '城市天際線',
    good: {
      id: 'img-landscape-517',
      title: '法蘭克福天際線夜色倒影',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Skyline_Frankfurt_am_Main.jpg/960px-Skyline_Frankfurt_am_Main.jpg',
      width: 3888,
      height: 2592,
      author: 'Nicolas Scheuer',
      license: 'CC BY-SA 2.5',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Skyline_Frankfurt_am_Main.jpg',
    },
    weak: {
      id: 'img-landscape-518',
      title: '霧霾午後的倫敦金融城',
      src: 'https://upload.wikimedia.org/wikipedia/commons/7/75/City_Skyline_-_geograph.org.uk_-_1649453.jpg',
      width: 640,
      height: 480,
      author: 'Colin Smith',
      license: 'CC BY-SA 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:City_Skyline_-_geograph.org.uk_-_1649453.jpg',
    },
    principles: ['golden-hour', 'dynamic-range', 'symmetry'],
    explanation:
      '好圖選在日落後拍攝，大樓亮起燈光、天空還留著紫灰色，河面把燈光倒映成第二排天際線，明暗對比恰到好處。另一張在霧霾的午後順光下拍，天空與建築同樣灰白，起重機、屋頂與船隻擠在一起，畫面平淡沒有立體感。城市遠景最怕平光與霾，等傍晚或雨後空氣乾淨時再拍，並找一片水面幫你把亮點加倍。',
  },
  {
    id: 'pair-018',
    theme: '室內樓梯',
    good: {
      id: 'img-architecture-509',
      title: '斯洛維尼亞國家博物館樓梯',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Staircase_of_the_National_Museum_of_Slovenia.jpg/960px-Staircase_of_the_National_Museum_of_Slovenia.jpg',
      width: 4608,
      height: 3456,
      author: 'Petar Milošević',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Staircase_of_the_National_Museum_of_Slovenia.jpg',
    },
    weak: {
      id: 'img-architecture-510',
      title: '匈牙利國家博物館樓梯大廳',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Budapest%2C_Hungarian_National_Museum%2C_staircase%2C_photo_2.jpg/960px-Budapest%2C_Hungarian_National_Museum%2C_staircase%2C_photo_2.jpg',
      width: 4269,
      height: 5434,
      author: 'Dguendel',
      license: 'CC BY 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Budapest,_Hungarian_National_Museum,_staircase,_photo_2.jpg',
    },
    principles: ['perspective', 'symmetry', 'leading-lines'],
    explanation:
      '好圖用魚眼鏡頭刻意把整個穹頂納進來，兩側欄杆與雕像對稱排開，階梯從下方一路把視線送到中央的胸像。另一張同樣站在中線，但相機大幅仰起，天花板占了一半以上、柱子向上收攏變形，樓梯本身被擠到畫面下緣。拍室內樓梯時，若不是刻意要拍天花板，可以把相機拿到腰部高度、保持水平，讓階梯成為帶路的線。',
  },
  {
    id: 'pair-019',
    theme: '老屋窗景',
    good: {
      id: 'img-architecture-511',
      title: '達斯半島紅窗與木牆',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Fischerkirche_%28window%29%2C_Born_a._Dar%C3%9F.jpg/960px-Fischerkirche_%28window%29%2C_Born_a._Dar%C3%9F.jpg',
      width: 6000,
      height: 3922,
      author: 'Radomianin',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Fischerkirche_(window),_Born_a._Dar%C3%9F.jpg',
    },
    weak: {
      id: 'img-architecture-512',
      title: '阿姆斯特丹石造門廊與窗',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Old_stone_facade_with_gate_and_windows%2C_Amsterdam_old_city_-_free_photo%2C_Fons_Heijnsbroek.jpg/960px-Old_stone_facade_with_gate_and_windows%2C_Amsterdam_old_city_-_free_photo%2C_Fons_Heijnsbroek.jpg',
      width: 5984,
      height: 4488,
      author: 'Fons Heijnsbroek',
      license: 'CC0',
      licenseUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Old_stone_facade_with_gate_and_windows,_Amsterdam_old_city_-_free_photo,_Fons_Heijnsbroek.jpg',
    },
    principles: ['symmetry', 'simplify', 'color-harmony'],
    explanation:
      '好圖正對窗戶拍攝，紅色窗框與百葉在深棕色木板牆上左右對稱，橫向木紋提供穩定的節奏，全畫面只有紅、白、棕三色，主體一眼就看到。另一張想拍拱門與鐵窗，但拍攝角度偏斜，左窗與右門互相拉扯，前方的兒童座椅與腳踏車擋住門的下半部，灰色石材與黑色鐵件也讓色彩偏沉。拍建築細部時，先退一步等前景淨空，再正面對齊，畫面就會安定下來。',
  },
  {
    id: 'pair-020',
    theme: '高山風景',
    good: {
      id: 'img-landscape-519',
      title: '阿爾尼湖區木屋與山峰',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Landscape_Arnisee-region.JPG/960px-Landscape_Arnisee-region.JPG',
      width: 3008,
      height: 2000,
      author: 'Simon Koopmann',
      license: 'CC BY-SA 2.5',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Landscape_Arnisee-region.JPG',
    },
    weak: {
      id: 'img-landscape-520',
      title: '薩彥嶺的冰川谷地',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Mountain_landscape%2C_Glacial_troughs%2C_Ergaki%2C_Sayan_Mountains%2C_Siberia.jpg/960px-Mountain_landscape%2C_Glacial_troughs%2C_Ergaki%2C_Sayan_Mountains%2C_Siberia.jpg',
      width: 6000,
      height: 4000,
      author: 'Vyacheslav Argenberg',
      license: 'CC BY 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Mountain_landscape,_Glacial_troughs,_Ergaki,_Sayan_Mountains,_Siberia.jpg',
    },
    principles: ['depth-layers', 'subject-placement', 'dynamic-range'],
    explanation:
      '好圖從綿延的草地與紅色木屋往上疊到雲霧繚繞的山峰，前中後三層分得很清楚，小屋的紅棕色在一片綠中成為視線落點，山體的明暗也保留完整。另一張的視野同樣壯闊，但天空被雲層壓得灰白、山谷大面積在陰影裡，右前方一塊深色岩石又貼在邊緣，畫面沒有可以當主角的東西。拍大山時，找一個有顏色或形狀的前景，並等雲層放出一點光。',
  },
  {
    id: 'pair-021',
    theme: '秋天紅葉',
    good: {
      id: 'img-still-life-505',
      title: '逆光下的紅色白楊葉',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Red_aspen_leaves_by_Myrstigen_1.jpg/960px-Red_aspen_leaves_by_Myrstigen_1.jpg',
      width: 4587,
      height: 3058,
      author: 'W.carter',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Red_aspen_leaves_by_Myrstigen_1.jpg',
    },
    weak: {
      id: 'img-still-life-506',
      title: '庭院裡的紅楓樹',
      src: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/%22Autumn_Leaves%22_-_geograph.org.uk_-_60824.jpg',
      width: 640,
      height: 480,
      author: 'Tom Courtney',
      license: 'CC BY-SA 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:%22Autumn_Leaves%22_-_geograph.org.uk_-_60824.jpg',
    },
    principles: ['light-direction', 'simplify', 'depth-of-field'],
    explanation:
      '好圖讓陽光從葉子背後穿透，每一片葉子都像被點亮，深色失焦的樹林背景把橘紅色襯得更亮，一根枝條斜切畫面就夠了。另一張的紅楓本身很漂亮，但陰天的平光讓紅色略顯沉悶，右下角闖進一台白色汽車，左側的樹叢與石牆也在爭注意。拍秋葉時試著繞到樹的另一側，讓光線從葉子後方來，再挪一步把車子裁出畫面。',
  },
  {
    id: 'pair-022',
    theme: '寺廟建築',
    good: {
      id: 'img-architecture-513',
      title: '玉佛寺白牆前經過的僧侶',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Temple_of_the_Emerald_Buddha.jpg/960px-Temple_of_the_Emerald_Buddha.jpg',
      width: 4705,
      height: 3141,
      author: 'Nawit science',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Temple_of_the_Emerald_Buddha.jpg',
    },
    weak: {
      id: 'img-architecture-514',
      title: '鄭王廟庭園與守門夜叉',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Wat_Arun_or_the_Temple_of_Dawn_Photo_Don_Ramey_Logan.jpg/960px-Wat_Arun_or_the_Temple_of_Dawn_Photo_Don_Ramey_Logan.jpg',
      width: 4240,
      height: 2682,
      author: 'Don Ramey Logan',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Wat_Arun_or_the_Temple_of_Dawn_Photo_Don_Ramey_Logan.jpg',
    },
    principles: ['symmetry', 'moment', 'golden-hour'],
    explanation:
      '好圖在雨後的清晨等到一位橘色僧侶走過白牆前方，雨水積成的水面把整排尖塔倒映成完整的鏡像，天空是柔和的藍與粉，一個小小的人影就讓建築有了故事。另一張在正午拍寺門，構圖對稱工整，但天空灰白、光線平淡，門口的遊客與兩側盆栽也讓畫面略顯零碎。同樣的地點，早一點到、等一個路過的人，照片就會從紀錄變成畫面。',
  },
  {
    id: 'pair-023',
    theme: '晨霧景色',
    good: {
      id: 'img-landscape-521',
      title: '上西利西亞的霧中林道',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Morning_fog_in_Upper_Silesia.jpg/960px-Morning_fog_in_Upper_Silesia.jpg',
      width: 4553,
      height: 3035,
      author: 'Pudelek',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Morning_fog_in_Upper_Silesia.jpg',
    },
    weak: {
      id: 'img-landscape-522',
      title: '晨霧中的華沙街景',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Morning_fog_in_Warszawa%2C_2025.03%2C_04.jpg/960px-Morning_fog_in_Warszawa%2C_2025.03%2C_04.jpg',
      width: 1564,
      height: 880,
      author: 'Chris Olszewski',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Morning_fog_in_Warszawa,_2025.03,_04.jpg',
    },
    principles: ['leading-lines', 'exposure', 'negative-space'],
    explanation:
      '好圖讓一條柏油路從畫面下方直直消失在霧裡，左側結霜的樹一棵棵由清晰漸淡，霧氣成了乾淨的留白，亮部與樹幹的暗部都保留了細節。另一張正對著霧中的太陽拍，右上角亮成一團白斑，建築與天空都灰濛濛連在一起，前景的草地與長凳又缺少方向感。拍霧景時，找一條路、一排樹或欄杆把視線帶進霧裡，並避開直射的太陽。',
  },
  {
    id: 'pair-024',
    theme: '狗狗人像',
    good: {
      id: 'img-people-animals-505',
      title: '仰望主人的黑色搜救犬',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/DSC09611a_Search_and_Rescue_Dog%2C_Austrian_Red_Cross_Perchtoldsdorf%2C_2024-10.jpg/960px-DSC09611a_Search_and_Rescue_Dog%2C_Austrian_Red_Cross_Perchtoldsdorf%2C_2024-10.jpg',
      width: 3195,
      height: 4260,
      author: 'Aciarium',
      license: 'CC BY 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:DSC09611a_Search_and_Rescue_Dog,_Austrian_Red_Cross_Perchtoldsdorf,_2024-10.jpg',
    },
    weak: {
      id: 'img-people-animals-506',
      title: '庭院裡追噴水的狗',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Dog_vs_Hose_%283574805712%29.jpg/960px-Dog_vs_Hose_%283574805712%29.jpg',
      width: 3504,
      height: 2332,
      author: 'Zach Dischner',
      license: 'CC BY 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Dog_vs_Hose_(3574805712).jpg',
    },
    principles: ['depth-of-field', 'perspective', 'sharpness'],
    explanation:
      '好圖蹲到與狗同高，用側面特寫拍它仰望的表情，淺景深把背景化成一片柔和的米色，焦點落在眼睛，黑色毛髮的光澤都很清楚。另一張的瞬間其實很可愛，但從站姿俯拍讓狗顯得小，正午頂光下狗臉略暗、水珠與草地一樣鮮綠搶眼，狗的臉部也因為快速移動而稍微模糊。拍寵物先把手機放低到它的視線高度，靠近一點讓背景自然虛化。',
  },
  {
    id: 'pair-025',
    theme: '山中湖泊',
    good: {
      id: 'img-landscape-523',
      title: '高加索扎格丹湖群',
      src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Zagedan_Lakes%2C_Mountain_cirque%2C_Caucasus_Mountains.jpg/960px-Zagedan_Lakes%2C_Mountain_cirque%2C_Caucasus_Mountains.jpg',
      width: 4912,
      height: 3264,
      author: 'Vyacheslav Argenberg',
      license: 'CC BY 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/4.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Zagedan_Lakes,_Mountain_cirque,_Caucasus_Mountains.jpg',
    },
    weak: {
      id: 'img-landscape-524',
      title: '柯利福德湖畔的樹',
      src: 'https://upload.wikimedia.org/wikipedia/commons/c/cf/Trees_on_the_shore_of_Colliford_Lake_-_geograph.org.uk_-_1450235.jpg',
      width: 640,
      height: 480,
      author: 'Rod Allday',
      license: 'CC BY-SA 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Trees_on_the_shore_of_Colliford_Lake_-_geograph.org.uk_-_1450235.jpg',
    },
    principles: ['depth-layers', 'exposure', 'subject-placement'],
    explanation:
      '好圖從前景的碎石與草地、中景的湛藍湖水到後方的岩峰層層推進，湖面放在下三分處，陽光把綠與藍都照得飽滿。另一張想拍湖畔的樹，但陰天逆光讓樹幹與枝葉幾乎變成黑色剪影，天空又偏白，樹擺在畫面正中間、湖只剩後方一條窄帶，前景則是空蕩的草地。這種情況可以側著光拍樹，或直接對著樹幹點測光，並把樹移到一側讓湖露出來。',
  },
]
